from fastapi import APIRouter, Depends
from datetime import datetime, timezone
from app.database import db
from app.auth import get_current_user
import uuid
from html import escape

router = APIRouter()


DOC_BLUEPRINTS = {
    "network_diagram": {
        "label": "Network topology", "sections": ["Scope & source data", "WAN connectivity", "Network segments", "Managed devices", "Risks & follow-up"],
        "description": "A technician-ready infrastructure topology summary generated from enrolled device data.",
    },
    "asset_inventory": {
        "label": "Asset inventory", "sections": ["Scope & source data", "Asset summary", "Managed devices", "Operating systems", "Lifecycle follow-up"],
        "description": "An asset register summary generated from the enrolled device inventory.",
    },
    "disaster_recovery": {
        "label": "Disaster recovery plan", "sections": ["Scope & assumptions", "Critical assets", "Recovery sequence", "Validation checklist", "Risks & follow-up"],
        "description": "A recovery planning baseline based on known managed devices and support records.",
    },
    "security_baseline": {
        "label": "Security baseline", "sections": ["Scope & source data", "Security posture", "Managed endpoints", "Validation checklist", "Risks & follow-up"],
        "description": "A security review baseline built from enrolled endpoint and operational data.",
    },
    "backup_recovery": {
        "label": "Backup & recovery runbook", "sections": ["Scope & source data", "Recovery priorities", "Protected assets", "Recovery validation", "Risks & follow-up"],
        "description": "A technician recovery runbook baseline for validating backup readiness and restoration steps.",
    },
    "operational_handover": {
        "label": "Operational handover", "sections": ["Service overview", "Support dependencies", "Managed assets", "Handover checklist", "Risks & follow-up"],
        "description": "An operational handover baseline for onboarding, escalation, or service-transition work.",
    },
    "software_licensing": {
        "label": "Software & licensing summary", "sections": ["Scope & source data", "Licensing review", "Managed endpoints", "Validation checklist", "Risks & follow-up"],
        "description": "A software and licensing review baseline based on managed endpoints and service records.",
    },
}


async def _build_document(client_name: str, doc_type: str, title: str, current_user: dict):
    client_record = await db.clients.find_one({"name": client_name}, {"_id": 0, "id": 1, "name": 1})
    client_id = (client_record or {}).get("id")
    devices = await db.devices.find({"client_id": client_id}, {"_id": 0, "id": 1, "name": 1, "hostname": 1, "device_type": 1, "type": 1, "status": 1, "os": 1, "os_name": 1, "ip_address": 1}).to_list(500) if client_id else []
    blueprint = DOC_BLUEPRINTS.get(doc_type, DOC_BLUEPRINTS["asset_inventory"])
    type_counts = {}
    for device in devices:
        kind = device.get("device_type") or device.get("type") or "Unclassified"
        type_counts[kind] = type_counts.get(kind, 0) + 1
    online_count = sum(1 for device in devices if str(device.get("status", "")).lower() == "online")
    review_count = len(devices) - online_count
    device_rows = "".join(
        f"<tr><td><strong>{escape(str(device.get('hostname') or device.get('name') or 'Unnamed device'))}</strong></td><td>{escape(str(device.get('device_type') or device.get('type') or 'Unclassified'))}</td><td>{escape(str(device.get('os_name') or device.get('os') or 'Unknown'))}</td><td><span class='nx-doc-status nx-doc-status--{escape(str(device.get('status') or 'unknown').lower())}'>{escape(str(device.get('status') or 'Unknown'))}</span></td></tr>"
        for device in devices[:100]
    ) or "<tr><td colspan='4'>No enrolled devices were available when this document was generated.</td></tr>"
    type_summary = ", ".join(f"{count} {kind}" for kind, count in sorted(type_counts.items())) or "No device classification data available"
    safe_client = escape(client_name)
    safe_title = escape(title or f"{client_name} — {blueprint['label']}")
    generated_by = escape(str(current_user.get("name") or "NexusMSP"))
    content_html = f"""
      <article class='nx-auto-doc'>
        <header class='nx-auto-doc__hero'><div><p class='nx-auto-doc__eyebrow'>NEXUSMSP · GENERATED BASELINE</p><h1>{safe_title}</h1><p class='nx-auto-doc__lede'>{escape(blueprint['description'])}</p></div><div class='nx-auto-doc__stamp'><span>DOCUMENT STATUS</span><strong>Needs technician review</strong><small>Generated from current inventory</small></div></header>
        <section class='nx-auto-doc__meta'><div><span>CLIENT</span><strong>{safe_client}</strong></div><div><span>GENERATED BY</span><strong>{generated_by}</strong></div><div><span>SOURCE</span><strong>Enrolled device inventory</strong></div><div><span>CLASSIFICATION</span><strong>Internal operational record</strong></div></section>
        <section class='nx-auto-doc__callout'><strong>Review required</strong><p>This is a live-inventory baseline. Confirm network, vendor, recovery, and change details before relying on it for production work or client-facing reporting.</p></section>
        <section><div class='nx-auto-doc__section-head'><span>01</span><div><h2>{escape(blueprint['sections'][0])}</h2><p>Inventory snapshot at the time of generation</p></div></div><div class='nx-auto-doc__metrics'><div><span>ENROLLED ASSETS</span><strong>{len(devices)}</strong></div><div><span>ONLINE</span><strong>{online_count}</strong></div><div><span>REQUIRES REVIEW</span><strong>{review_count}</strong></div><div><span>ASSET MIX</span><strong>{escape(type_summary)}</strong></div></div></section>
        <section><div class='nx-auto-doc__section-head'><span>02</span><div><h2>{escape(blueprint['sections'][1])}</h2><p>Technician validation guide</p></div></div><div class='nx-auto-doc__guidance'><div><strong>Validate</strong><p>Compare this baseline against approved diagrams, firewall configuration, vendor portals, and client records.</p></div><div><strong>Capture</strong><p>Attach diagrams, exports, recovery evidence, and exception notes to make this record operationally complete.</p></div><div><strong>Act</strong><p>Create follow-up tickets for unclassified assets, offline devices, or information that needs confirmation.</p></div></div></section>
        <section><div class='nx-auto-doc__section-head'><span>03</span><div><h2>{escape(blueprint['sections'][2])}</h2><p>Managed device inventory</p></div></div><div class='nx-auto-doc__table-wrap'><table><thead><tr><th>Device</th><th>Type</th><th>Operating system</th><th>Current status</th></tr></thead><tbody>{device_rows}</tbody></table></div></section>
        <section><div class='nx-auto-doc__section-head'><span>04</span><div><h2>{escape(blueprint['sections'][3])}</h2><p>Completion checklist</p></div></div><ul class='nx-auto-doc__checklist'><li>Confirm this document against authoritative client and vendor records.</li><li>Add diagrams, configuration exports, and recovery evidence.</li><li>Log exceptions and link remediation tickets.</li></ul></section>
        <footer class='nx-auto-doc__footer'><span>Generated by NexusMSP</span><span>Internal operational documentation · Review before use</span></footer>
      </article>
    """
    now = datetime.now(timezone.utc).isoformat()
    return {
        "id": f"adoc-{uuid.uuid4().hex[:8]}", "client_id": client_id, "client_name": client_name,
        "doc_type": doc_type, "title": title or f"{client_name} — {blueprint['label']}",
        "description": blueprint["description"], "sections": blueprint["sections"], "content_html": content_html,
        "source_snapshot": {"device_count": len(devices), "device_types": type_counts, "generated_from": "enrolled_devices"},
        "generated_at": now, "generated_by": current_user.get("name"), "status": "needs_review", "completion_note": "Generated from the current NexusMSP device inventory. Technician review is required before operational or client-facing use.",
    }

@router.get("/capacity-planner/overview")
async def get_capacity_overview(current_user: dict = Depends(get_current_user)):
    techs = await db.users.find({"role": {"$in": ["admin", "technician"]}}, {"_id": 0, "id": 1, "name": 1, "role": 1}).to_list(50)
    tickets_30d = await db.tickets.count_documents({})
    devices = await db.devices.count_documents({})
    clients = await db.clients.count_documents({})
    tech_count = len(techs)
    tickets_per_tech = round(tickets_30d / tech_count, 1) if tech_count else None
    devices_per_tech = round(devices / tech_count, 1) if tech_count else None
    return {
        "current": {"technicians": tech_count, "total_clients": clients, "total_devices": devices, "tickets_per_tech": tickets_per_tech, "devices_per_tech": devices_per_tech, "utilization_pct": None, "evidence_state": "partial_evidence"},
        "forecast": {"recommended_techs": None, "hiring_needed": None, "bottleneck": "not_assessed", "message": "Capacity planning requires recorded schedules and time-entry history."},
        "trend": [],
    }

@router.get("/auto-documentation/documents")
async def get_auto_docs(current_user: dict = Depends(get_current_user)):
    # The legacy implementation inserted a permanent "generating" record and
    # never scheduled a worker. Complete any of those stale placeholders so the
    # workspace can no longer imply background work is occurring.
    await db.auto_generated_docs.update_many(
        {"status": "generating"},
        {"$set": {"status": "needs_review", "completion_note": "Legacy request was not processed by a worker. Regenerate to create a review-required inventory baseline.", "completed_at": datetime.now(timezone.utc).isoformat()}},
    )
    docs = await db.auto_generated_docs.find({}, {"_id": 0}).sort("generated_at", -1).to_list(50)
    return docs

@router.post("/auto-documentation/generate")
async def generate_doc(data: dict, current_user: dict = Depends(get_current_user)):
    client_name = (data.get("client_name") or "").strip()
    doc_type = data.get("doc_type") or "asset_inventory"
    if not client_name:
        return {"error": "A client is required"}
    doc = await _build_document(client_name, doc_type, (data.get("title") or "").strip(), current_user)
    await db.auto_generated_docs.insert_one(doc)
    doc.pop("_id", None)
    return doc


@router.get("/auto-documentation/documents/{document_id}")
async def get_auto_doc(document_id: str, current_user: dict = Depends(get_current_user)):
    return await db.auto_generated_docs.find_one({"id": document_id}, {"_id": 0}) or {"error": "Document not found"}


@router.post("/auto-documentation/documents/{document_id}/regenerate")
async def regenerate_auto_doc(document_id: str, current_user: dict = Depends(get_current_user)):
    existing = await db.auto_generated_docs.find_one({"id": document_id}, {"_id": 0})
    if not existing:
        return {"error": "Document not found"}
    refreshed = await _build_document(existing.get("client_name", ""), existing.get("doc_type", "asset_inventory"), existing.get("title", ""), current_user)
    refreshed["id"] = document_id
    refreshed["regenerated_at"] = datetime.now(timezone.utc).isoformat()
    await db.auto_generated_docs.update_one({"id": document_id}, {"$set": refreshed})
    return refreshed


@router.post("/auto-documentation/upgrade-baselines")
async def upgrade_auto_doc_baselines(current_user: dict = Depends(get_current_user)):
    """Bring legacy/sample documents onto the current professional document system."""
    documents = await db.auto_generated_docs.find({}, {"_id": 0}).to_list(200)
    upgraded = 0
    for existing in documents:
        if not existing.get("client_name"):
            continue
        refreshed = await _build_document(
            existing["client_name"], existing.get("doc_type", "asset_inventory"), existing.get("title", ""), current_user,
        )
        refreshed["id"] = existing["id"]
        refreshed["upgraded_at"] = datetime.now(timezone.utc).isoformat()
        refreshed["completion_note"] = "Refreshed onto the NexusMSP professional document baseline from current inventory."
        await db.auto_generated_docs.update_one({"id": existing["id"]}, {"$set": refreshed})
        upgraded += 1
    return {"message": f"{upgraded} document(s) upgraded to the current document system", "upgraded": upgraded}
