from fastapi import APIRouter, Depends
from app.auth import get_current_user

router = APIRouter()

TICKET_TEMPLATES = [
    {"id": "tt-1", "name": "Password Reset", "category": "access", "priority": "medium", "description": "User unable to login or forgot password. Reset credentials and verify MFA.", "checklist": ["Verify user identity via phone/email", "Reset password in AD/M365", "Set temporary password", "Instruct user to change on next login", "Verify MFA enrollment", "Confirm access restored"]},
    {"id": "tt-2", "name": "New User Onboarding", "category": "onboarding", "priority": "medium", "description": "Setup new employee with full IT access and equipment.", "checklist": ["Create AD account", "Assign M365 license", "Configure email + Teams", "Setup MFA", "Deploy laptop/workstation", "Install standard software", "Configure VPN access", "Add to security groups", "Send welcome email with credentials", "Schedule orientation call"]},
    {"id": "tt-3", "name": "Network Connectivity Down", "category": "network", "priority": "critical", "description": "Site or user experiencing complete network outage.", "checklist": ["Confirm scope (single user vs site-wide)", "Check ISP status page", "Remote into firewall/switch", "Check WAN interface status", "Verify DHCP lease pool", "Check DNS resolution", "Test failover WAN if available", "Escalate to ISP if external", "Update client on ETA"]},
    {"id": "tt-4", "name": "Email Not Working", "category": "email", "priority": "high", "description": "User unable to send/receive emails. Check M365 and client config.", "checklist": ["Check M365 service health", "Verify mailbox is active", "Test webmail access", "Check Outlook profile", "Verify autodiscover DNS", "Check mail flow rules", "Review quarantine for blocked messages", "Test send/receive"]},
    {"id": "tt-5", "name": "Printer Issue", "category": "hardware", "priority": "low", "description": "Printer offline, jamming, or not printing from workstation.", "checklist": ["Check printer power and connectivity", "Verify printer IP and DNS entry", "Clear print queue", "Reinstall printer driver if needed", "Test print from another workstation", "Check toner/paper levels"]},
    {"id": "tt-6", "name": "VPN Connection Failed", "category": "access", "priority": "high", "description": "Remote user unable to connect to company VPN.", "checklist": ["Verify VPN client version", "Check VPN gateway status", "Verify user credentials", "Check MFA token", "Test alternate VPN profile", "Review firewall VPN logs", "Check certificate expiry"]},
    {"id": "tt-7", "name": "Slow Computer", "category": "performance", "priority": "medium", "description": "User reporting slow performance on workstation.", "checklist": ["Check CPU/RAM/Disk usage (Task Manager)", "Run disk cleanup", "Check for pending Windows updates", "Scan for malware", "Review startup programs", "Check disk health (S.M.A.R.T.)", "Consider SSD upgrade if HDD"]},
    {"id": "tt-8", "name": "Backup Failure Alert", "category": "backup", "priority": "critical", "description": "Automated backup job has failed. Investigate and remediate.", "checklist": ["Check backup console for error details", "Verify target storage is accessible", "Check disk space on backup target", "Verify VSS writers are healthy", "Re-run failed job manually", "Check for locked files", "Verify backup agent is running", "Test restore from last good backup"]},
    {"id": "tt-9", "name": "Security Incident", "category": "security", "priority": "critical", "description": "Potential security breach or suspicious activity detected.", "checklist": ["Isolate affected system(s)", "Document initial findings", "Check EDR for alerts", "Review login audit logs", "Check for lateral movement", "Reset compromised credentials", "Scan for malware/ransomware", "Notify client stakeholders", "Document timeline of events", "Implement remediation steps"]},
    {"id": "tt-10", "name": "Server Unreachable", "category": "server", "priority": "critical", "description": "Critical server not responding to pings or RDP.", "checklist": ["Verify from multiple sources (not just one)", "Check hypervisor console (Hyper-V/VMware)", "Check physical power if on-prem", "Review event logs for crash", "Check disk space", "Verify services are running", "Check firewall rules", "Restart server if safe to do so"]},
    {"id": "tt-11", "name": "Software Installation Request", "category": "request", "priority": "low", "description": "User requesting new software to be installed.", "checklist": ["Verify software is approved", "Check licensing availability", "Deploy via RMM or manual install", "Configure application settings", "Test functionality", "Update software inventory"]},
    {"id": "tt-12", "name": "User Offboarding", "category": "offboarding", "priority": "medium", "description": "Employee departing — revoke all access and recover assets.", "checklist": ["Disable AD account", "Revoke M365 license", "Convert mailbox to shared (if needed)", "Remove from all security groups", "Revoke VPN/remote access", "Wipe mobile device if BYOD", "Collect physical assets", "Transfer ownership of files/data", "Archive mailbox", "Update client contact list"]},
]

ONBOARDING_TEMPLATES = [
    {"id": "ob-1", "name": "New Client IT Audit", "category": "audit", "description": "Comprehensive initial audit of a new client's IT environment.", "steps": ["Network topology mapping", "Server & workstation inventory", "Software licensing audit", "Security posture assessment", "Backup verification", "Domain & DNS review", "M365 tenant review", "ISP & connectivity review", "Print environment audit", "Document findings and recommendations"]},
    {"id": "ob-2", "name": "Microsoft 365 Migration", "category": "migration", "description": "Migrate client email and data to Microsoft 365.", "steps": ["Assess current email system", "Plan migration timeline", "Provision M365 tenant", "Configure domains and DNS (MX, SPF, DKIM, DMARC)", "Migrate mailboxes (staged or cutover)", "Configure Teams & SharePoint", "Setup MFA for all users", "Deploy Outlook on endpoints", "Verify mail flow", "Decommission old system"]},
    {"id": "ob-3", "name": "Security Baseline Setup", "category": "security", "description": "Deploy standard security stack for new managed client.", "steps": ["Deploy EDR/AV on all endpoints", "Configure firewall rules", "Enable MFA on all accounts", "Setup security awareness training", "Configure email filtering", "Deploy backup solution", "Setup SIEM monitoring", "Document incident response plan", "Schedule quarterly security review"]},
    {"id": "ob-4", "name": "RMM Agent Deployment", "category": "deployment", "description": "Deploy monitoring agents across all client devices.", "steps": ["Generate site-specific installer", "Deploy to servers first", "Deploy to workstations", "Verify all agents checking in", "Configure monitoring policies", "Setup alert thresholds", "Configure patch management", "Verify remote access", "Document any excluded devices"]},
]

SLA_TEMPLATES = [
    {"id": "sla-1", "name": "Platinum - Enterprise", "tier": "platinum", "response_critical": "15 min", "response_high": "30 min", "response_medium": "2 hr", "response_low": "4 hr", "resolve_critical": "2 hr", "resolve_high": "4 hr", "resolve_medium": "8 hr", "resolve_low": "24 hr", "availability": "99.99%", "support_hours": "24/7/365", "features": ["Dedicated account manager", "Quarterly business reviews", "Priority escalation path", "On-site support included"]},
    {"id": "sla-2", "name": "Gold - Business", "tier": "gold", "response_critical": "30 min", "response_high": "1 hr", "response_medium": "4 hr", "response_low": "8 hr", "resolve_critical": "4 hr", "resolve_high": "8 hr", "resolve_medium": "1 day", "resolve_low": "2 days", "availability": "99.9%", "support_hours": "Mon-Fri 7am-7pm + Emergency", "features": ["Named support contacts", "Monthly reporting", "Remote support included"]},
    {"id": "sla-3", "name": "Silver - Standard", "tier": "silver", "response_critical": "1 hr", "response_high": "2 hr", "response_medium": "8 hr", "response_low": "1 day", "resolve_critical": "8 hr", "resolve_high": "1 day", "resolve_medium": "2 days", "resolve_low": "3 days", "availability": "99.5%", "support_hours": "Mon-Fri 8am-6pm", "features": ["Email and phone support", "Quarterly reporting"]},
    {"id": "sla-4", "name": "Bronze - Basic", "tier": "bronze", "response_critical": "2 hr", "response_high": "4 hr", "response_medium": "1 day", "response_low": "2 days", "resolve_critical": "1 day", "resolve_high": "2 days", "resolve_medium": "3 days", "resolve_low": "5 days", "availability": "99%", "support_hours": "Mon-Fri 9am-5pm", "features": ["Email support", "Annual review"]},
]

RUNBOOK_TEMPLATES = [
    {"id": "rb-1", "name": "Server Down - Emergency Response", "category": "incident", "severity": "critical", "steps": ["Acknowledge alert and log incident", "Verify server status from monitoring", "Attempt remote connection (RDP/SSH)", "Check hypervisor/cloud console", "Review event/system logs", "If hardware: Contact DC/vendor support", "If software: Restart critical services", "If OS crash: Initiate safe-mode boot", "Verify services restored", "Run health check scripts", "Notify client with status update", "Document root cause and resolution"]},
    {"id": "rb-2", "name": "Ransomware Response", "category": "security", "severity": "critical", "steps": ["IMMEDIATELY isolate affected systems (pull network)", "Do NOT power off encrypted systems", "Document everything with timestamps", "Identify ransomware variant if possible", "Check backup integrity (DO NOT connect to infected network)", "Report to management and legal", "Consider engaging IR firm", "Preserve evidence for forensics", "Begin restoration from clean backups", "Change ALL passwords domain-wide", "Patch vulnerability that allowed entry", "Conduct post-incident review"]},
    {"id": "rb-3", "name": "New Employee IT Setup", "category": "onboarding", "severity": "low", "steps": ["Receive new hire form from HR/manager", "Create Active Directory account", "Assign to appropriate security groups", "Provision M365 license (E3/E5/BP)", "Configure email and Teams", "Enroll MFA (Authenticator app)", "Prepare workstation/laptop", "Install standard software stack", "Configure VPN profile", "Setup printer access", "Create documentation/credentials pack", "Schedule welcome call with user"]},
    {"id": "rb-4", "name": "Client Offboarding", "category": "offboarding", "severity": "medium", "steps": ["Confirm offboarding scope with client", "Export and archive all client data", "Remove client devices from RMM", "Remove monitoring and alerts", "Disable client VPN tunnels", "Transfer domain registrar access", "Provide M365 admin credentials to client", "Remove backup configurations", "Decommission dedicated infrastructure", "Generate final documentation package", "Process final invoice", "Update CRM status"]},
    {"id": "rb-5", "name": "Firewall Rule Change", "category": "network", "severity": "medium", "steps": ["Document change request details", "Verify business justification", "Review current rule set", "Plan rule change (source, dest, port, action)", "Backup current firewall config", "Implement change during maintenance window", "Test connectivity through new rule", "Verify no unintended side effects", "Update documentation/network diagram", "Close change request"]},
    {"id": "rb-6", "name": "Backup Failure Investigation", "category": "backup", "severity": "high", "steps": ["Check backup console for error code", "Verify target storage accessibility", "Check available disk space", "Review VSS writer status", "Check for locked/open files", "Verify backup agent service running", "Review recent system changes", "Retry failed backup manually", "Test restore from last good backup", "Document findings and resolution", "Verify next scheduled backup succeeds"]},
]

SCRIPT_TEMPLATES = [
    {"id": "st-1", "name": "Disk Space Cleanup", "category": "maintenance", "os_target": "windows", "language": "powershell", "content": "# Disk Space Cleanup Script\n$Before = (Get-PSDrive C).Free / 1GB\nWrite-Host \"Free space before: $([math]::Round($Before, 2)) GB\"\n\n# Clear temp files\nRemove-Item -Path \"$env:TEMP\\*\" -Recurse -Force -ErrorAction SilentlyContinue\nRemove-Item -Path \"C:\\Windows\\Temp\\*\" -Recurse -Force -ErrorAction SilentlyContinue\n\n# Clear Windows Update cache\nStop-Service -Name wuauserv -Force -ErrorAction SilentlyContinue\nRemove-Item -Path \"C:\\Windows\\SoftwareDistribution\\Download\\*\" -Recurse -Force -ErrorAction SilentlyContinue\nStart-Service -Name wuauserv\n\n# Empty recycle bin\nClear-RecycleBin -Force -ErrorAction SilentlyContinue\n\n$After = (Get-PSDrive C).Free / 1GB\nWrite-Host \"Free space after: $([math]::Round($After, 2)) GB\"\nWrite-Host \"Recovered: $([math]::Round($After - $Before, 2)) GB\""},
    {"id": "st-2", "name": "AD User Audit", "category": "security", "os_target": "windows", "language": "powershell", "content": "# Active Directory User Audit\nImport-Module ActiveDirectory\n\nWrite-Host '=== Disabled Accounts ===' -ForegroundColor Yellow\nGet-ADUser -Filter {Enabled -eq $false} -Properties LastLogonDate | Select Name, LastLogonDate | Format-Table\n\nWrite-Host '=== Accounts Not Logged In 90+ Days ===' -ForegroundColor Yellow\n$CutOff = (Get-Date).AddDays(-90)\nGet-ADUser -Filter {LastLogonDate -lt $CutOff -and Enabled -eq $true} -Properties LastLogonDate | Select Name, LastLogonDate | Format-Table\n\nWrite-Host '=== Password Never Expires ===' -ForegroundColor Red\nGet-ADUser -Filter {PasswordNeverExpires -eq $true -and Enabled -eq $true} | Select Name | Format-Table\n\nWrite-Host '=== Admin Group Members ===' -ForegroundColor Cyan\nGet-ADGroupMember 'Domain Admins' | Select Name | Format-Table"},
    {"id": "st-3", "name": "Windows Update Check", "category": "patching", "os_target": "windows", "language": "powershell", "content": "# Windows Update Status Check\nWrite-Host 'Checking Windows Update status...' -ForegroundColor Cyan\n\n$Session = New-Object -ComObject Microsoft.Update.Session\n$Searcher = $Session.CreateUpdateSearcher()\n$Results = $Searcher.Search('IsInstalled=0')\n\nWrite-Host \"`nPending Updates: $($Results.Updates.Count)\" -ForegroundColor Yellow\nforeach ($Update in $Results.Updates) {\n    $Severity = if ($Update.MsrcSeverity) { $Update.MsrcSeverity } else { 'Unrated' }\n    Write-Host \"  [$Severity] $($Update.Title)\"\n}\n\n$History = $Searcher.GetTotalHistoryCount()\n$LastUpdate = $Searcher.QueryHistory(0, 1) | Select Date\nWrite-Host \"`nLast update installed: $($LastUpdate.Date)\" -ForegroundColor Green"},
    {"id": "st-4", "name": "Service Health Check", "category": "monitoring", "os_target": "windows", "language": "powershell", "content": "# Critical Service Health Check\n$Services = @('Spooler','W32Time','DNS','DHCP','WinRM','EventLog','LanmanServer','LanmanWorkstation','RpcSs','Netlogon','wuauserv')\n\nWrite-Host '=== Service Health Check ===' -ForegroundColor Cyan\nforeach ($Svc in $Services) {\n    $Service = Get-Service -Name $Svc -ErrorAction SilentlyContinue\n    if ($Service) {\n        $Color = if ($Service.Status -eq 'Running') { 'Green' } else { 'Red' }\n        Write-Host \"  $($Svc.PadRight(25)) $($Service.Status)\" -ForegroundColor $Color\n    } else {\n        Write-Host \"  $($Svc.PadRight(25)) NOT FOUND\" -ForegroundColor DarkGray\n    }\n}"},
    {"id": "st-5", "name": "Backup Verification", "category": "backup", "os_target": "windows", "language": "powershell", "content": "# Backup Verification Script\nWrite-Host '=== Backup Status Check ===' -ForegroundColor Cyan\n\n# Check Windows Server Backup\n$WBSummary = Get-WBSummary -ErrorAction SilentlyContinue\nif ($WBSummary) {\n    Write-Host \"Last Backup: $($WBSummary.LastSuccessfulBackupTime)\"\n    Write-Host \"Next Backup: $($WBSummary.NextBackupTime)\"\n    Write-Host \"Result: $($WBSummary.LastBackupResultHR)\"\n} else {\n    Write-Host 'Windows Server Backup not configured' -ForegroundColor Yellow\n}\n\n# Check VSS Writers\nWrite-Host \"`n=== VSS Writer Status ===\" -ForegroundColor Cyan\nvssadmin list writers | Select-String 'Writer name','State' | ForEach-Object { Write-Host $_ }"},
    {"id": "st-6", "name": "Network Diagnostic", "category": "network", "os_target": "windows", "language": "powershell", "content": "# Network Diagnostic Script\nWrite-Host '=== Network Diagnostics ===' -ForegroundColor Cyan\n\nWrite-Host \"`nIP Configuration:\" -ForegroundColor Yellow\nGet-NetIPAddress -AddressFamily IPv4 | Where InterfaceAlias -notmatch 'Loopback' | Select InterfaceAlias, IPAddress, PrefixLength | Format-Table\n\nWrite-Host 'DNS Servers:' -ForegroundColor Yellow\nGet-DnsClientServerAddress -AddressFamily IPv4 | Where ServerAddresses | Select InterfaceAlias, ServerAddresses | Format-Table\n\nWrite-Host 'Gateway:' -ForegroundColor Yellow\nGet-NetRoute -DestinationPrefix '0.0.0.0/0' | Select NextHop, InterfaceAlias | Format-Table\n\nWrite-Host 'DNS Resolution Test:' -ForegroundColor Yellow\nResolve-DnsName google.com -Type A | Select Name, IPAddress | Format-Table\n\nWrite-Host 'Connectivity Test:' -ForegroundColor Yellow\nTest-Connection -ComputerName 8.8.8.8 -Count 2 | Select Address, ResponseTime | Format-Table"},
    {"id": "st-7", "name": "SSL Certificate Check", "category": "security", "os_target": "cross-platform", "language": "powershell", "content": "# SSL Certificate Expiry Check\nparam([string[]]$Domains = @('google.com','microsoft.com'))\n\nWrite-Host '=== SSL Certificate Check ===' -ForegroundColor Cyan\nforeach ($Domain in $Domains) {\n    try {\n        $Request = [System.Net.HttpWebRequest]::Create(\"https://$Domain\")\n        $Request.Timeout = 5000\n        $Response = $Request.GetResponse()\n        $Cert = $Request.ServicePoint.Certificate\n        $Expiry = [datetime]::Parse($Cert.GetExpirationDateString())\n        $DaysLeft = ($Expiry - (Get-Date)).Days\n        $Color = if ($DaysLeft -lt 30) { 'Red' } elseif ($DaysLeft -lt 60) { 'Yellow' } else { 'Green' }\n        Write-Host \"  $($Domain.PadRight(30)) Expires: $($Expiry.ToString('yyyy-MM-dd'))  ($DaysLeft days)\" -ForegroundColor $Color\n        $Response.Close()\n    } catch {\n        Write-Host \"  $($Domain.PadRight(30)) ERROR: $($_.Exception.Message)\" -ForegroundColor Red\n    }\n}"},
    {"id": "st-8", "name": "Linux System Health", "category": "monitoring", "os_target": "linux", "language": "bash", "content": "#!/bin/bash\n# Linux System Health Check\necho '=== System Health Check ==='\necho ''\necho 'Hostname:' $(hostname)\necho 'Uptime:' $(uptime -p)\necho 'Kernel:' $(uname -r)\necho ''\necho '=== Disk Usage ==='\ndf -h | grep -E '^/dev' | awk '{print $1, $5, $6}'\necho ''\necho '=== Memory ==='\nfree -h | grep -E 'Mem|Swap'\necho ''\necho '=== CPU Load ==='\nuptime | awk -F'load average:' '{print $2}'\necho ''\necho '=== Top 5 Processes by CPU ==='\nps aux --sort=-%cpu | head -6\necho ''\necho '=== Failed Services ==='\nsystemctl --failed --no-pager 2>/dev/null || echo 'systemctl not available'"},
]

@router.get("/templates/tickets")
async def get_ticket_templates(current_user: dict = Depends(get_current_user)):
    return TICKET_TEMPLATES

@router.get("/templates/onboarding")
async def get_onboarding_templates(current_user: dict = Depends(get_current_user)):
    return ONBOARDING_TEMPLATES

@router.get("/templates/sla")
async def get_sla_templates(current_user: dict = Depends(get_current_user)):
    return SLA_TEMPLATES

@router.get("/templates/runbooks")
async def get_runbook_templates(current_user: dict = Depends(get_current_user)):
    return RUNBOOK_TEMPLATES

@router.get("/templates/scripts")
async def get_script_templates(current_user: dict = Depends(get_current_user)):
    return SCRIPT_TEMPLATES
