from fastapi import APIRouter, HTTPException, Depends
from datetime import datetime, timezone
import uuid
import io
import logging
from app.database import db
from app.auth import get_current_user

logger = logging.getLogger(__name__)
router = APIRouter()

def generate_ticket_pdf(ticket, comments, whitelabel_config=None):
    """Generate a branded PDF of the ticket conversation history"""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Brand header
    company_name = "NexusOps"
    primary_color = (59, 130, 246)  # blue
    if whitelabel_config:
        company_name = whitelabel_config.get("company_name", "NexusOps")
        hex_color = whitelabel_config.get("primary_color", "#3B82F6").lstrip("#")
        if len(hex_color) == 6:
            primary_color = tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))

    # Header bar
    pdf.set_fill_color(*primary_color)
    pdf.rect(0, 0, 210, 25, 'F')
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_xy(10, 5)
    pdf.cell(0, 15, company_name, ln=True)

    # Ticket info
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(30)
    pdf.set_font("Helvetica", "B", 14)
    ticket_number = ticket.get("ticket_number", "N/A")
    pdf.cell(0, 8, f"Ticket {ticket_number}: {ticket.get('title', 'Untitled')}", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Status: {ticket.get('status', 'open').replace('_', ' ').title()}  |  Priority: {ticket.get('priority', 'medium').title()}  |  Client: {ticket.get('client_name', 'N/A')}", ln=True)
    pdf.cell(0, 6, f"Created: {ticket.get('created_at', 'N/A')[:19].replace('T', ' ')}", ln=True)
    pdf.ln(3)

    # Description
    if ticket.get("description"):
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, "Description", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        desc = ticket.get("description", "")[:2000]
        desc = desc.encode('latin-1', 'ignore').decode('latin-1')
        pdf.multi_cell(0, 5, desc)
        pdf.ln(3)

    # Separator
    pdf.set_draw_color(*primary_color)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # Conversation history
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Conversation History", ln=True)
    pdf.ln(2)

    # Filter out internal notes for client-facing PDF
    public_comments = [c for c in comments if not c.get("is_internal", False)]

    if not public_comments:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 6, "No public updates yet.", ln=True)
    else:
        for comment in sorted(public_comments, key=lambda x: x.get("created_at", ""), reverse=False):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*primary_color)
            user_name = comment.get("user_name", "System")
            created = comment.get("created_at", "")[:19].replace("T", " ")
            pdf.cell(0, 6, f"{user_name}  -  {created}", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            content = comment.get("content", "")[:3000]
            # Strip HTML tags and emojis for plain text
            import re
            content = re.sub(r'<[^>]+>', '', content)
            # Remove non-Latin1 characters (emojis, special unicode)
            content = content.encode('latin-1', 'ignore').decode('latin-1')
            pdf.multi_cell(0, 5, content)
            pdf.ln(3)
            # Light separator
            pdf.set_draw_color(200, 200, 200)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)

    # Footer
    pdf.set_y(-25)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, f"Generated by {company_name} on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", ln=True, align="C")
    pdf.cell(0, 5, "This is an automated notification. Please do not reply to this email.", ln=True, align="C")

    return pdf.output()


@router.post("/tickets/{ticket_id}/notify-client")
async def notify_client_with_pdf(ticket_id: str, data: dict, current_user: dict = Depends(get_current_user)):
    """Send email notification to client with PDF conversation history"""
    ticket = await db.tickets.find_one({"id": ticket_id}, {"_id": 0})
    if not ticket:
        raise HTTPException(status_code=404, detail="Ticket not found")

    # Get client email
    client_obj = await db.clients.find_one({"id": ticket.get("client_id")}, {"_id": 0})
    if not client_obj:
        raise HTTPException(status_code=404, detail="Client not found")

    recipient_email = data.get("email") or client_obj.get("email")
    if not recipient_email:
        raise HTTPException(status_code=400, detail="No email address found for client")

    # Get ticket conversation
    comments = await db.ticket_comments.find({"ticket_id": ticket_id}, {"_id": 0}).sort("created_at", 1).to_list(500)

    # Get white label config
    wl_config = await db.settings.find_one({"key": "whitelabel_options"}, {"_id": 0})
    whitelabel = wl_config.get("value", {}) if wl_config else {}

    # Generate PDF
    pdf_bytes = generate_ticket_pdf(ticket, comments, whitelabel)

    company_name = whitelabel.get("company_name", "NexusOps")
    ticket_number = ticket.get("ticket_number", "N/A")
    subject = data.get("subject", f"Ticket Update: {ticket_number} - {ticket.get('title', '')}")
    message_body = data.get("message", f"You have a new update on your ticket {ticket_number}. Please find the conversation history attached as a PDF.")

    html_body = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #3B82F6, #1D4ED8); padding: 20px; border-radius: 8px 8px 0 0;">
            <h2 style="color: white; margin: 0;">{company_name}</h2>
        </div>
        <div style="padding: 24px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
            <h3 style="color: #1f2937;">Ticket Update: {ticket_number}</h3>
            <p style="color: #4b5563;">{message_body}</p>
            <div style="background: #f3f4f6; padding: 16px; border-radius: 6px; margin: 16px 0;">
                <p style="margin: 4px 0; color: #6b7280;"><strong>Ticket:</strong> {ticket_number} - {ticket.get('title', '')}</p>
                <p style="margin: 4px 0; color: #6b7280;"><strong>Status:</strong> {ticket.get('status', 'open').replace('_', ' ').title()}</p>
                <p style="margin: 4px 0; color: #6b7280;"><strong>Priority:</strong> {ticket.get('priority', 'medium').title()}</p>
            </div>
            <p style="color: #9ca3af; font-size: 12px;">The full conversation history is attached as a PDF.</p>
        </div>
    </div>
    """

    from app.routers.email_utils import send_email
    delivery = await send_email(
        recipient_email,
        subject,
        html_body,
        category="ticket_comments",
        attachments=[{"filename": f"ticket_{ticket_number}_conversation.pdf", "content": bytes(pdf_bytes), "content_type": "application/pdf"}],
    )
    email_status = delivery.get("status", "failed")

    # Record the notification
    notif_record = {
        "id": str(uuid.uuid4()),
        "ticket_id": ticket_id,
        "ticket_number": ticket_number,
        "client_id": ticket.get("client_id"),
        "recipient_email": recipient_email,
        "subject": subject,
        "status": email_status,
        "delivery_message": delivery.get("message", ""),
        "sender_mailbox": delivery.get("sender"),
        "has_pdf": True,
        "sent_by": current_user["id"],
        "sent_by_name": current_user["name"],
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    await db.ticket_email_notifications.insert_one(notif_record)
    notif_record.pop("_id", None)

    return notif_record

@router.get("/tickets/{ticket_id}/notification-history")
async def get_ticket_notification_history(ticket_id: str, current_user: dict = Depends(get_current_user)):
    """Get email notification history for a ticket"""
    history = await db.ticket_email_notifications.find(
        {"ticket_id": ticket_id}, {"_id": 0}
    ).sort("created_at", -1).to_list(50)
    return history

@router.get("/tickets/{ticket_id}/download-pdf")
async def download_ticket_pdf(ticket_id: str, current_user: dict = Depends(get_current_user)):
    """Download ticket conversation as PDF"""
    from fastapi.responses import Response

    ticket = await db.tickets.find_one({"id": ticket_id}, {"_id": 0})
    if not ticket:
        raise HTTPException(status_code=404, detail="Ticket not found")

    comments = await db.ticket_comments.find({"ticket_id": ticket_id}, {"_id": 0}).sort("created_at", 1).to_list(500)

    wl_config = await db.settings.find_one({"key": "whitelabel_options"}, {"_id": 0})
    whitelabel = wl_config.get("value", {}) if wl_config else {}

    pdf_bytes = generate_ticket_pdf(ticket, comments, whitelabel)
    ticket_number = ticket.get("ticket_number", "ticket")

    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="ticket_{ticket_number}_conversation.pdf"'}
    )
