"""Durable product-idea registry for Nexus Foundation.

Ideas are deliberately separate from the committed product roadmap. Capturing
an idea does not claim it is approved, scheduled, funded, or released.
"""

from __future__ import annotations

import uuid
from collections import Counter
from datetime import datetime, timezone
from typing import Any

from app.database import db


IDEA_STATUSES = ("captured", "reviewing", "validated", "promoted", "parked", "rejected")
VALUE_AXES = ("saves_time", "reduces_stress", "increases_confidence", "creates_opportunity")

_IDEAS = (
    (326, "Digital Air Traffic Control", "operations", "Balance technician work using ticket load, expertise, location, and collision evidence.", (1, 1, 1, 0)),
    (327, "Living Customer", "experience", "Express customer health through calm, accessible motion and colour backed by health evidence.", (1, 1, 1, 0)),
    (328, "AI Whisper", "experience", "Offer quiet contextual guidance without interrupting the technician workflow.", (1, 1, 1, 0)),
    (329, "Universal Command History", "foundation", "Retain and replay technician, API, ticket, remote, and automation actions through one audit contract.", (1, 1, 1, 0)),
    (330, "Environment Ecosystem", "relationships", "Visualise how infrastructure, protection, services, and users depend on each other.", (1, 1, 1, 0)),
    (331, "Living API Explorer", "developer-experience", "Make connector requests, responses, latency, and failures observable in real time.", (1, 0, 1, 0)),
    (332, "AI Memory Threads", "intelligence", "Assemble every source-backed object related to a technician question into one explainable thread.", (1, 1, 1, 0)),
    (333, "Zero Waiting", "performance", "Predictively prefetch safe client context so primary workspaces feel immediate.", (1, 1, 0, 0)),
    (334, "Infinite Undo", "foundation", "Model changes with before/after state, reversible checkpoints, retention, and governed rollback.", (1, 1, 1, 0)),
    (335, "Live MSP Pulse", "experience", "Show platform freshness and degraded-heartbeat evidence without dashboard noise.", (1, 1, 1, 0)),
    (336, "AI Confidence Rings", "trust", "Display provenance and confidence for documentation, security, backups, billing, and automation.", (0, 1, 1, 0)),
    (337, "Reality Mode", "onsite", "Overlay verified asset and cabling context for onsite technicians using a device camera.", (1, 1, 1, 0)),
    (338, "AI Learns Your Style", "automation", "Suggest repeatable workflow improvements from a technician's approved action patterns.", (1, 1, 1, 0)),
    (339, "Living Network", "network", "Represent live topology, traffic, and failure propagation from observed telemetry.", (1, 1, 1, 0)),
    (340, "Customer Time Capsule", "history", "Compare a client's verified operational state at two retained points in time.", (1, 1, 1, 1)),
    (341, "AI Never Again", "automation", "Detect recurring issues and propose permanent remediation, policy, training, or replacement options.", (1, 1, 1, 1)),
    (342, "Digital Project Manager", "projects", "Make project risk, budget, progress, dependencies, and next actions understandable at a glance.", (1, 1, 1, 1)),
    (343, "Knowledge Constellations", "knowledge", "Reveal documentation relationships based on verified shared use and object links.", (1, 1, 1, 0)),
    (344, "AI Escalation Predictor", "service-desk", "Forecast SLA and customer escalation risk from explainable operational evidence.", (1, 1, 1, 1)),
    (345, "Human Memory Replacement", "knowledge", "Preserve decisions, workarounds, scripts, outcomes, and context as institutional memory.", (1, 1, 1, 1)),
    (346, "Why Is This Slow?", "endpoint", "Run a governed multi-signal endpoint investigation and return an evidence-backed explanation.", (1, 1, 1, 0)),
    (347, "Living Rack", "onsite", "Combine rack layout with observed temperature, power, health, and port state.", (1, 1, 1, 0)),
    (348, "AI Company Coach", "business", "Relate delivery, automation, staffing, and financial signals into explainable business guidance.", (1, 1, 1, 1)),
    (349, "Invisible Documentation", "knowledge", "Surface the right approved documentation inside the workflow that needs it.", (1, 1, 1, 0)),
    (350, "Calm Mission Brief", "experience", "Replace homepage overload with a concise evidence-backed overnight and today briefing.", (1, 1, 1, 1)),
    (351, "NexusOS Platform Mission", "strategy", "Evolve Nexus as a coherent MSP operating system with one identity, context model, permission vocabulary, billing engine, AI boundary, and audit contract.", (1, 1, 1, 1)),
    (352, "Living Knowledge", "knowledge", "Replace static documentation with source-backed knowledge that updates, scores confidence, and appears in context.", (1, 1, 1, 1)),
    (353, "Network Digital Twin", "network", "Represent verified ports, VLANs, cables, devices, sites, and dependencies as one time-aware operational model.", (1, 1, 1, 1)),
    (354, "Configuration Intelligence", "infrastructure", "Version, compare, explain, and govern configuration state across supported providers and managed assets.", (1, 1, 1, 1)),
    (355, "Nexus Exchange", "marketplace", "Share governed automation, policies, reports, documentation, templates, integrations, and industry packs.", (1, 1, 1, 1)),
    (356, "Nexus University", "training", "Provide role-aware technician labs, learning paths, certifications, and evidence-based skill development.", (1, 1, 1, 1)),
    (357, "Nexus Benchmark", "business", "Offer opt-in anonymised operational and financial comparisons with privacy and cohort safeguards.", (1, 0, 1, 1)),
    (358, "Nexus Autonomous MSP", "strategy", "Safely progress from recommendations to approved bounded autonomy while humans retain architecture, relationships, and high-impact decisions.", (1, 1, 1, 1)),
    (359, "Nexus Box", "hardware", "Explore a securely managed network appliance for routing, firewall, DNS, VPN, monitoring, backup gateway, and remote relay workloads.", (1, 1, 1, 1)),
    (360, "Nexus Sensor", "hardware", "Explore a small trusted discovery and telemetry appliance for client networks where the endpoint agent cannot provide coverage.", (1, 1, 1, 1)),
    (361, "Nexus Context Fabric", "foundation", "Preserve why records and controls exist, who requested and approved them, the business process involved, and the evidence supporting each relationship.", (1, 1, 1, 1)),
    (362, "Nexus Intelligence Layer", "intelligence", "Give every module one governed intelligence contract for explaining events, detecting patterns, recommending work, and proposing automation.", (1, 1, 1, 1), 351),
    (363, "Universal Object Model", "foundation", "Give every operational record the same identity, relationship, history, approval, attachment, task, and automation capabilities.", (1, 1, 1, 1), 352),
    (364, "Every Object Has a Timeline", "foundation", "Let every canonical object tell its own source-backed operational story without implying causation from event proximity.", (1, 1, 1, 0), 353),
    (365, "Universal Comments", "collaboration", "Write a comment once and attach it to multiple canonical objects without duplicating the underlying note.", (1, 1, 1, 0), 354),
    (366, "AI Memory Cards", "intelligence", "Provide a concise, provenance-aware object summary containing current state, risk, recent change, open work, and suggested next action.", (1, 1, 1, 0), 355),
    (367, "Health Everywhere", "trust", "Expose domain-appropriate health for every canonical object, including operational and commercial records.", (1, 1, 1, 1), 356),
    (368, "Confidence Everywhere", "trust", "Show how trustworthy an object's state is using freshness, provenance, verification, and evidence coverage.", (0, 1, 1, 0), 357),
    (369, "Business Impact Everywhere", "experience", "Require alerts and degraded states to explain affected people, services, business processes, and recorded financial exposure.", (1, 1, 1, 1), 358),
    (370, "One Relationship Engine", "relationships", "Use one evidence-backed relationship graph for operational, commercial, knowledge, identity, and infrastructure objects.", (1, 1, 1, 1), 359),
    (371, "AI Context Engine", "intelligence", "Assemble the relevant records, prior fixes, assets, risks, documentation, preferences, and current work for the task in view.", (1, 1, 1, 0), 360),
    (372, "Contextual Screen Assistant", "intelligence", "Use one governed assistant that adopts the permissions, vocabulary, and verified context of the active workspace.", (1, 1, 1, 1), 361),
    (373, "Universal Simulation", "governance", "Preview material actions, affected objects, policy checks, approvals, rollback limits, and likely outcomes before execution.", (1, 1, 1, 0), 362),
    (374, "AI Standardiser", "operations", "Compare client state with an approved standard and explain every material deviation before proposing remediation.", (1, 1, 1, 1), 363),
    (375, "Operations Calendar", "operations", "Unify maintenance, renewals, projects, arrivals, warranties, certificates, licences, and staff availability on one governed calendar.", (1, 1, 1, 0), 364),
    (376, "AI Design Review", "automation", "Review draft automations for loops, duplicated work, security boundaries, performance risk, and existing equivalent workflows.", (1, 1, 1, 0), 365),
    (377, "Universal Versioning", "foundation", "Apply version history, comparison, approval, retention, and governed rollback to supported Nexus objects.", (1, 1, 1, 0), 366),
    (378, "MSP Digital Twin", "business", "Model the MSP's own verified staffing, workload, revenue, growth, delivery risk, and capacity relationships.", (1, 1, 1, 1), 367),
    (379, "AI Operational Debt", "operations", "Identify stale, duplicated, unused, or unsupported automations, documents, scripts, monitors, and policies with evidence.", (1, 1, 1, 0), 368),
    (380, "Trust Graph", "trust", "Score trust from authorship, verification, freshness, usage, provenance, and contradiction evidence rather than permissions alone.", (1, 1, 1, 0), 369),
    (381, "Nexus Knowledge Network", "strategy", "Explore explicitly opted-in, privacy-preserving learning about which changes, hardware, automations, and operating patterns improve MSP outcomes.", (1, 1, 1, 1), 370),
    (382, "The Nexus Button", "experience", "Provide one context-aware entry point that explains the active workspace and suggests the safest useful next actions.", (1, 1, 1, 0), 371),
    (383, "Living Workspace", "experience", "Adapt workspace emphasis to verified time, workload, deadlines, and technician responsibilities without hiding core navigation.", (1, 1, 0, 0), 372),
    (384, "AI Detects Confusion", "intelligence", "Detect repeated navigation and search loops locally, then offer a concise explanation without monitoring unrelated user behaviour.", (1, 1, 1, 0), 373),
    (385, "Smart Hover Actions", "experience", "Reveal safe, relevant quick actions after clear pointer intent while retaining accessible keyboard and touch alternatives.", (1, 1, 0, 0), 374),
    (386, "Every Metric Explains Itself", "experience", "Make meaningful charts, counts, icons, and status signals open their source records, definitions, or filtered evidence.", (1, 1, 1, 0), 375),
    (387, "Living Sidebar", "experience", "Prioritise contextual navigation while preserving predictable information architecture and user control.", (1, 1, 0, 0), 376),
    (388, "Predictive Prefetch", "performance", "Prefetch only safe, likely next read models from local workflow context so navigation feels immediate without taking action.", (1, 1, 0, 0), 377),
    (389, "Universal Inspector", "foundation", "Open properties, health, confidence, history, relationships, notes, and source evidence in one reusable side inspector.", (1, 1, 1, 0), 378),
    (390, "Journey Breadcrumbs", "experience", "Preserve the technician's navigational journey and object context so they can safely return to earlier decision points.", (1, 1, 1, 0), 379),
    (391, "Universal Floating Search", "experience", "Keep fast cross-object search available without forcing the technician into a modal or new workspace.", (1, 1, 0, 0), 380),
    (392, "AI Cursor", "intelligence", "Explore opt-in pointer-adjacent explanations and suggestions with strict motion, accessibility, and interruption controls.", (1, 1, 1, 0), 381),
    (393, "Living Tooltips", "experience", "Turn tooltips into small accessible evidence previews for complex status and metrics rather than hiding critical controls in hover-only UI.", (1, 1, 1, 0), 382),
    (394, "Operational Theme Signals", "experience", "Use restrained, accessible workspace accents to reflect verified normal, degraded, or critical operational state.", (0, 1, 1, 0), 383),
    (395, "Focus Bubble", "experience", "Reduce surrounding visual noise while a technician performs high-attention ticket or change work, with an explicit exit.", (1, 1, 0, 0), 384),
    (396, "Workflow Heat Trails", "analytics", "Use privacy-aware aggregate workflow telemetry to identify repeated navigation sequences worth simplifying or automating.", (1, 1, 1, 1), 385),
    (397, "Universal Timeline Slider", "history", "Explore time-aware object state using retained snapshots and clear gaps where historical state is unavailable.", (1, 1, 1, 0), 386),
    (398, "Relationship Inspector", "relationships", "Preview verified object relationships and their evidence with accessible motion and a static fallback.", (1, 1, 1, 0), 387),
    (399, "Technician AI Workspace", "experience", "Assemble a role-aware homepage from verified responsibilities, priorities, and preferences while keeping manual controls.", (1, 1, 1, 0), 388),
    (400, "Evidence-Built Dashboards", "analytics", "Propose temporary dashboards from current operational questions with visible metric definitions and sources.", (1, 1, 1, 0), 389),
    (401, "One Canvas", "experience", "Explore an infinite operational canvas for relationship-heavy investigations without replacing efficient list and form workflows.", (1, 1, 1, 0), 390),
    (402, "Living Reports", "reporting", "Publish governed report views that can refresh from current authorised data while preserving immutable generated snapshots for audit.", (1, 1, 1, 1), 391),
    (403, "Universal Diff", "foundation", "Compare supported objects, versions, policies, documents, commercial records, and snapshots through one evidence-aware diff contract.", (1, 1, 1, 0), 392),
    (404, "Smart Empty States", "experience", "Explain what an empty state means and suggest safe proactive work without manufacturing urgency.", (1, 1, 1, 0), 393),
    (405, "Contextual Micro-Learning", "training", "Offer optional, role-aware lessons at the point of work without obstructing experienced technicians.", (0, 1, 1, 1), 394),
    (406, "Daily Improvement Prompt", "training", "Suggest one small evidence-backed improvement such as documenting, standardising, or automating recurring work.", (1, 1, 1, 0), 395),
    (407, "AI Sketch", "knowledge", "Convert a technician sketch into a draft network model that requires verification before becoming documentation.", (1, 1, 1, 0), 396),
    (408, "Universal Preview", "experience", "Preview authorised object context and recent evidence without losing the current workflow.", (1, 1, 1, 0), 397),
    (409, "Live MSP Heartbeat", "business", "Summarise the MSP's current operational state in one explainable pulse backed by drill-down evidence.", (1, 1, 1, 1), 398),
    (410, "Zero Dashboard", "experience", "Allow the absence of actionable work to be the primary dashboard outcome instead of filling space with vanity widgets.", (1, 1, 1, 0), 399),
    (411, "Nexus Memory Engine", "intelligence", "Turn attributable actions, environments, outcomes, time, feedback, and documentation changes into privacy-governed operational memory.", (1, 1, 1, 1), 400),
    (412, "Liquid Glass UI", "experience", "Explore restrained translucent depth and pointer-aware highlights without reducing contrast or content legibility.", (0, 1, 0, 1), 401),
    (413, "Magnetic Buttons", "experience", "Explore subtle pointer-proximity feedback for primary actions with static, keyboard, touch, and reduced-motion equivalents.", (1, 1, 0, 0), 402),
    (414, "Purposeful Particle Field", "experience", "Use a sparse optional particle field to communicate active AI processing rather than as permanent decoration.", (0, 1, 1, 0), 403),
    (415, "Responsive Click Ripples", "experience", "Provide brief pointer-origin feedback so actions feel acknowledged while preserving immediate response and accessibility.", (0, 1, 1, 0), 404),
    (416, "Bubble Notifications", "experience", "Explore calm, stackable notifications with predictable focus, dismissal, persistence, and audit behaviour.", (1, 1, 1, 0), 405),
    (417, "Milestone Shooting Star", "experience", "Reserve one brief celebratory motion for verified major milestones rather than routine work.", (0, 1, 0, 1), 406),
    (418, "Stateful Animated Gradients", "experience", "Let restrained gradients communicate verified state improvement or degradation without relying on colour alone.", (0, 1, 1, 0), 407),
    (419, "Live Service Globe", "visualisation", "Explore a navigable client and service-location globe where geography materially aids outage and delivery decisions.", (1, 1, 1, 1), 408),
    (420, "Automation Flow Lines", "automation", "Animate governed workflow progress so technicians can distinguish queued, running, blocked, failed, and completed steps.", (1, 1, 1, 0), 409),
    (421, "Relationship Data Pulses", "relationships", "Use optional pulses on verified connections to communicate observed activity without implying unmeasured traffic.", (0, 1, 1, 0), 410),
    (422, "Operational Heat Maps", "visualisation", "Map CPU, memory, network, workload, and risk intensity using accessible scales and exact drill-down evidence.", (1, 1, 1, 0), 411),
    (423, "Outage Atmosphere", "experience", "Use a restrained degraded-state atmosphere during verified major incidents without compromising focus or accessibility.", (0, 1, 1, 0), 412),
    (424, "AI Aurora", "experience", "Use a slow optional aurora to distinguish active AI work from idle or recommendation-ready states.", (0, 1, 1, 0), 413),
    (425, "Health DNA", "visualisation", "Explore a distinctive health visual only where it communicates multiple verified contributing signals more clearly than a chart.", (0, 1, 1, 1), 414),
    (426, "Crystal Cards", "experience", "Use restrained depth and light response for premium surfaces while maintaining consistent semantic hierarchy.", (0, 1, 0, 1), 415),
    (427, "Fast Context Transition", "performance", "Use a short transition to preserve spatial context while switching clients, never masking actual loading time.", (1, 1, 1, 0), 416),
    (428, "Floating Widgets", "experience", "Explore extremely subtle ambient depth for passive widgets with no motion in minimal or reduced-motion modes.", (0, 1, 0, 0), 417),
    (429, "Critical Incident Energy", "experience", "Communicate verified critical escalation and resolution through restrained intensity changes rather than continuous alarming motion.", (1, 1, 1, 0), 418),
    (430, "Time-Aware Dark Mode", "experience", "Explore opt-in time-aware dark tones without changing semantic colours or overriding technician preferences.", (0, 1, 0, 0), 419),
    (431, "First-Customer Celebration", "experience", "Celebrate the first completed onboarding once, accessibly, and never during repeat operational work.", (0, 1, 0, 1), 420),
    (432, "Ocean Mission Control", "experience", "Explore a calm optional ambient background for passive monitoring screens with motion controls.", (0, 1, 0, 0), 421),
    (433, "Context Compass", "navigation", "Show the technician's current object and relationship direction when it reduces disorientation in deep investigations.", (1, 1, 1, 0), 422),
    (434, "Discovery Radar", "visualisation", "Visualise active authorised discovery progress, results, failures, and coverage gaps without inventing devices.", (1, 1, 1, 0), 423),
    (435, "Galaxy Search", "visualisation", "Explore relationship-distance search visualisation alongside an efficient accessible result list.", (1, 1, 1, 0), 424),
    (436, "Morphing Cards", "experience", "Preserve spatial continuity when a card expands into detail, with static and reduced-motion alternatives.", (1, 1, 0, 0), 425),
    (437, "Client Portal Transition", "experience", "Explore a brief client-context transition that never delays navigation or disguises tenant switching.", (0, 1, 1, 0), 426),
    (438, "Mirror Highlights", "experience", "Use restrained pointer-aware reflection for premium surfaces without obscuring content.", (0, 1, 0, 0), 427),
    (439, "Knowledge Growth Motion", "knowledge", "Communicate verified documentation coverage growth with accessible progress motion and exact evidence.", (0, 1, 1, 0), 428),
    (440, "Thermal Warning Motion", "endpoint", "Use a small semantic thermal indicator only when measured temperature crosses an approved threshold.", (1, 1, 1, 0), 429),
    (441, "Healthy Cooling Effect", "experience", "Use a calm blue breathing state for verified stable systems with motion disabled in minimal modes.", (0, 1, 1, 0), 430),
    (442, "Client Solar System", "relationships", "Explore an orbital relationship view while retaining a precise accessible graph and list alternative.", (1, 1, 1, 1), 431),
    (443, "Ink Search Transition", "experience", "Use a brief fluid expansion for search only when it improves spatial continuity and responsiveness.", (1, 1, 0, 0), 432),
    (444, "Knowledge Constellation Motion", "knowledge", "Animate verified knowledge links gently while preserving evidence, labels, and a static alternative.", (1, 1, 1, 0), 433),
    (445, "Nebula Background", "experience", "Offer a faint optional dark-mode texture that never competes with operational content.", (0, 1, 0, 0), 434),
    (446, "Optional Interface Sound", "accessibility", "Explore opt-in, independently controlled action, success, and notification sounds with no audio by default.", (0, 1, 1, 0), 435),
    (447, "Weighted Drag Physics", "experience", "Use restrained drag response to clarify placement and collision while keeping keyboard reordering available.", (1, 1, 0, 0), 436),
    (448, "Animated Numbers", "experience", "Interpolate changed counts briefly while preserving the exact final value and reduced-motion behaviour.", (0, 1, 1, 0), 437),
    (449, "Revenue Recovery Moment", "billing", "Acknowledge verified recovered revenue briefly without gamifying routine financial work.", (0, 1, 1, 1), 438),
    (450, "Dynamic Depth", "experience", "Explore subtle contextual shadows while keeping depth stable enough for predictable hierarchy.", (0, 1, 0, 0), 439),
    (451, "Accessible Hover Lift", "experience", "Use a small lift to identify interactive cards with equivalent focus-visible feedback.", (1, 1, 0, 0), 440),
    (452, "Cinematic Loading", "experience", "Replace generic spinners with honest staged progress only when the system can report real loading phases.", (0, 1, 1, 0), 441),
    (453, "Morphing Status Icons", "experience", "Animate verified state transitions between warning, repair, and healthy without hiding labels or history.", (1, 1, 1, 0), 442),
    (454, "Live Data Rivers", "integrations", "Visualise attributable data movement between providers, Nexus, billing, and documents with latency and failure evidence.", (1, 1, 1, 1), 443),
    (455, "Semantic Colour Contract", "foundation", "Standardise blue for work, green for healthy, amber for attention, red for immediate action, and violet for AI with non-colour cues.", (1, 1, 1, 0), 444),
    (456, "Ambient Intelligence", "foundation", "Let surfaces quietly communicate recommendations, revenue gaps, active sessions, progress, and resolved state without noisy notifications.", (1, 1, 1, 1), 445),
    (457, "Water Physics", "experience", "Explore weighted drag interactions only where spatial movement improves understanding, with keyboard reordering and reduced-motion alternatives.", (1, 1, 0, 0), 401),
    (458, "Adaptive Lighting", "experience", "Use restrained pointer-aware illumination to clarify interactive depth without darkening essential information.", (0, 1, 0, 0), 402),
    (459, "Parallax Depth", "experience", "Explore minimal optional depth response for premium surfaces while preserving stability, performance, and accessibility.", (0, 1, 0, 0), 403),
    (460, "Air Resistance", "experience", "Use consistent deceleration for draggable surfaces so movement communicates weight without slowing task completion.", (1, 1, 0, 0), 404),
    (461, "Living Icons", "experience", "Animate small icon details only when they communicate measured activity or state, never as permanent decoration.", (0, 1, 1, 0), 405),
    (462, "Energy Trails", "experience", "Explore brief trails for meaningful movement or data transfer with strict motion and performance controls.", (0, 1, 0, 0), 406),
    (463, "Premium Glass", "experience", "Create consistent high-contrast premium surfaces with restrained edge light and depth.", (0, 1, 0, 1), 407),
    (464, "Temperature Colours", "endpoint", "Map measured thermal state through a continuous accessible scale with exact temperatures and threshold evidence.", (1, 1, 1, 0), 408),
    (465, "Magnetic Layouts", "experience", "Provide predictable snapping, collision handling, keyboard placement, and saved layout state for configurable workspaces.", (1, 1, 0, 0), 409),
    (466, "Liquid Progress", "experience", "Explore distinctive progress motion only when backed by real measured completion and a numeric accessible equivalent.", (0, 1, 1, 0), 410),
    (467, "AI Thinking Graph", "intelligence", "Show actual retrieval, tool, validation, and response stages rather than fake neural activity or typing.", (0, 1, 1, 0), 411),
    (468, "Live Earth", "visualisation", "Combine client geography, provider paths, weather, and outages when those verified relationships improve operational decisions.", (1, 1, 1, 1), 412),
    (469, "Vortex Search", "experience", "Explore a short search transition while preserving instant keyboard focus, result order, and reduced-motion behaviour.", (1, 1, 0, 0), 413),
    (470, "Sunrise Dashboard", "experience", "Offer opt-in time-aware ambience without changing semantic state colours or reducing contrast.", (0, 1, 0, 0), 414),
    (471, "Workspace Sleep Mode", "experience", "Calm optional ambient motion after inactivity while keeping live status, alerts, and accessibility unchanged.", (0, 1, 0, 0), 415),
    (472, "Continuous Morphing", "experience", "Preserve spatial continuity between supported cards, dialogs, and detail views without delaying navigation.", (1, 1, 0, 0), 416),
    (473, "Ocean Navigation", "experience", "Explore optional depth transitions for passive navigation with minimal and static equivalents.", (0, 1, 0, 0), 417),
    (474, "Camera Motion", "experience", "Use a consistent zoom, pan, and focus language only when it explains navigational origin and destination.", (1, 1, 1, 0), 418),
    (475, "Living Borders", "foundation", "Use restrained semantic edge light to communicate verified health, attention, critical, work, and AI states.", (0, 1, 1, 0), 419),
    (476, "Success Energy", "automation", "Animate verified workflow completion across attributable steps so technicians can see the completed path.", (1, 1, 1, 0), 420),
    (477, "Live Rack LEDs", "infrastructure", "Reflect measured rack power and link states through small accessible indicators with timestamps and source evidence.", (1, 1, 1, 0), 421),
    (478, "AI Reasoning Stages", "intelligence", "Visualise attributable AI retrieval, tool calls, policy checks, and validation stages without exposing private chain-of-thought.", (1, 1, 1, 0), 422),
    (479, "Infinite Operational Space", "visualisation", "Explore zoomable customer-to-event relationships alongside efficient lists, search, forms, and accessibility alternatives.", (1, 1, 1, 1), 423),
    (480, "Knowledge Tree", "knowledge", "Represent verified documentation maturity and coverage through a tree metaphor with exact underlying measures.", (0, 1, 1, 1), 424),
    (481, "Bubble Menus", "experience", "Explore radial context actions only where discoverability, touch, and keyboard access remain equal or better.", (1, 1, 0, 0), 425),
    (482, "Motion Rhythm", "foundation", "Standardise durations, easing, distance, interruption, and reduced-motion behaviour across Nexus interactions.", (1, 1, 1, 0), 426),
    (483, "Living Background", "experience", "Offer barely perceptible optional ambient movement for passive workspaces with no effect on content or state.", (0, 1, 0, 0), 427),
    (484, "Remote Signal Waves", "remote", "Visualise measured remote-session latency and connection quality through labelled waves and exact telemetry.", (1, 1, 1, 0), 428),
    (485, "AI Aura", "intelligence", "Use the shared violet ambient signal when a source-backed AI recommendation is available.", (1, 1, 1, 0), 429),
    (486, "Client Colour Memory", "navigation", "Assign stable accessible client accents as a secondary navigation cue without replacing names, logos, or tenant boundaries.", (1, 1, 1, 0), 430),
    (487, "Nexus Desired State", "control-plane", "Define service-tier outcomes once, continuously compare every client against them, and create governed remediation rather than vendor-specific checklists.", (1, 1, 1, 1)),
    (488, "Nexus Access", "identity", "Broker privileged access through just-in-time grants, approvals, expiry, session evidence and credential-rotation boundaries across supported providers.", (1, 1, 1, 1)),
    (489, "Nexus Certificate & Domain Intelligence", "network", "Unify domain, certificate, registrar, DNS, expiry and dangerous-change evidence around the canonical client and service records.", (1, 1, 1, 1)),
    (490, "Nexus Network Source of Truth", "network", "Evolve verified discovery into IPAM, DHCP, DNS, subnets, conflict detection and documentation without creating a second disconnected inventory.", (1, 1, 1, 1)),
    (491, "Nexus Vendor Intelligence", "integrations", "Treat provider health, contracts, escalation paths, renewal evidence and data-feed failures as accountable operational records.", (1, 1, 1, 1)),
    (492, "Nexus Contract Intelligence", "commercial", "Compare service agreements with live delivery, exclusions, obligations, service quantities and billing evidence before proposing a review.", (1, 1, 1, 1)),
    (493, "Nexus Exposure Intelligence", "security", "Relate externally visible assets, domains, certificates, leaked-credential signals and provider posture to the affected client and accountable response path.", (1, 1, 1, 1)),
    (494, "Nexus Resilience Continuity", "resilience", "Unify recovery plans, emergency contacts, alternate communications, exercises, verified restores and post-incident evidence beyond backup status alone.", (1, 1, 1, 1)),
    (495, "Nexus Client Experience", "endpoint", "Measure user-impact signals such as login, collaboration, Wi-Fi, application and device experience with privacy-aware, explainable evidence.", (1, 1, 1, 1)),
    (496, "Nexus Autonomous Finance", "commercial", "Reconcile provider quantities, services, labour, contracts and invoice readiness through approval-aware, evidence-backed automation.", (1, 1, 1, 1)),
    (497, "Nexus Shadow Mode", "automation", "Observe repeatable Nexus-side workflows and propose bounded automation candidates without silently recording unrelated activity or taking action.", (1, 1, 1, 1)),
    (498, "Nexus Second Brain", "intelligence", "Answer operational why-questions from attributable tickets, changes, documentation, chat and decisions while clearly showing source evidence and uncertainty.", (1, 1, 1, 1)),
    (499, "Nexus Data Protection & Governance", "data-governance", "Discover and evidence sensitive-data location, oversharing, retention, stale data and governed remediation across connected providers.", (1, 1, 1, 1)),
    (500, "Nexus Application Manager", "endpoint", "Govern the full application lifecycle: catalogue, approved version, test ring, canary, staged deployment, verification and rollback evidence.", (1, 1, 1, 1)),
    (501, "Nexus Configuration as Code", "control-plane", "Version customer standards as reviewable policy, calculate the impact of a standard change, and stage supported remediations behind approvals.", (1, 1, 1, 1)),
    (502, "Nexus Test Environment", "reliability", "Run representative, non-production simulations for scripts, packages, policies, automations, agent updates and connectors before broad rollout.", (1, 1, 1, 1)),
    (503, "Nexus Dependency Registry", "relationships", "Preserve verified software, infrastructure, network, service and business-process dependencies as evidence for blast-radius and root-cause work.", (1, 1, 1, 1)),
    (504, "Nexus Technical Standards Library", "operations", "Turn preferred hardware, service stacks, configurations and support patterns into versioned standards that guide consistent customer delivery.", (1, 1, 1, 1)),
    (505, "Nexus Lifecycle Intelligence", "commercial", "Track technology from procurement through support, ageing, replacement, disposal and the resulting approved commercial workflow.", (1, 1, 1, 1)),
    (506, "Nexus Universal Connector Builder", "integrations", "Create reviewable draft connectors from an OpenAPI contract or documented API, with object mappings, scoped credentials and a test suite before publication.", (1, 1, 1, 1)),
    (507, "Nexus Data Importer", "foundation", "Map legacy CSV, spreadsheet, JSON, XML and database exports to canonical Nexus objects through a reviewable, reversible migration workflow.", (1, 1, 1, 1)),
    (508, "Nexus Data Quality Engine", "foundation", "Detect duplicate, orphaned, stale and inconsistent canonical records, then propose safe merges or corrections with retained evidence.", (1, 1, 1, 1)),
    (509, "Nexus Promise Engine", "customer-success", "Turn explicit customer commitments captured in authorised Nexus records into accountable follow-up work without treating inferred sentiment as fact.", (1, 1, 1, 1)),
    (510, "Nexus Assurance", "resilience", "Continuously prove critical business outcomes through authorised tests and retained evidence, rather than reporting that a service merely appears available.", (1, 1, 1, 1)),
    (511, "Nexus Customer Twin", "relationships", "Connect verified business processes to their people, applications and infrastructure so incidents explain customer impact, not only component status.", (1, 1, 1, 1)),
    (512, "Nexus Trust Centre", "trust", "Publish a deliberately scoped, public or private trust record from approved security, availability, resilience and data-residency evidence.", (1, 1, 1, 1)),
    (513, "Nexus Vendor Risk", "security", "Assess customer supplier risk through owned evidence, agreements, data access, questionnaires, incidents, renewals and responsible reviewers.", (1, 1, 1, 1)),
    (514, "Nexus Architecture Designer", "design", "Turn an approved business and site requirement into a reviewable architecture, BOM, project, procurement, configuration and documentation flow.", (1, 1, 1, 1)),
    (515, "Nexus Site Survey", "onsite", "Provide an offline-capable onsite capture workflow for spaces, racks, cabling, equipment, photos and verification before documentation publication.", (1, 1, 1, 1)),
    (516, "Nexus Network Commissioning", "network", "Commission a verified asset into its intended client, site, rack, policy, monitoring, documentation and billing scope through controlled validation.", (1, 1, 1, 1)),
    (517, "Nexus Hardware Health Intelligence", "endpoint", "Use observed fleet telemetry to identify explainable hardware-risk patterns without presenting predicted failure as certainty.", (1, 1, 1, 1)),
    (518, "Nexus Compatibility Intelligence", "intelligence", "Relate approved vendor evidence, local incidents and compatibility outcomes before proposing a material operating-system, application or firmware change.", (1, 1, 1, 1)),
    (519, "Nexus Problem & Fix Exchange", "marketplace", "Share opt-in, privacy-preserving detection, remediation, verification and rollback packs through a governed review and publication boundary.", (1, 1, 1, 1)),
    (520, "Nexus Experiment", "reliability", "Compare authorised operational interventions with a controlled cohort and clear success criteria before standardising an automation or policy.", (1, 1, 1, 1)),
    (521, "Nexus Cost of IT", "business", "Model attributable technology, service, labour and resilience costs using declared assumptions so strategic recommendations remain explainable.", (1, 1, 1, 1)),
    (522, "Nexus Service Designer", "commercial", "Create managed-service packages from inclusions, controls, cost, margin, SLA, workflow, contract, reporting and billing definitions.", (1, 1, 1, 1)),
    (523, "Nexus Service Delivery Verification", "commercial", "Compare contracted and billed services with provider and agent evidence to surface both underdelivery and commercial leakage for review.", (1, 1, 1, 1)),
    (524, "Nexus Contract Autopilot", "commercial", "Prepare a renewal recommendation from attributable service quantity, delivery, profitability, risk, SLA and lifecycle evidence, always awaiting owner approval.", (1, 1, 1, 1)),
    (525, "Nexus Customer Intelligence & Federation", "platform", "Model business-critical customer context and support delegated, regional, data-residency-aware operations without bypassing tenancy boundaries.", (1, 1, 1, 1)),
    (526, "Nexus Service & Journey Intelligence", "reliability", "Model a customer-visible service and approved synthetic journeys across its dependencies, golden signals, service objectives and verification evidence.", (1, 1, 1, 1)),
    (527, "Nexus Client Care Rules", "customer-success", "Apply declared client preferences, VIP/business-impact context and human-touch requirements to routing, automation and communications.", (1, 1, 1, 1)),
    (528, "Nexus Commitment, Decision & Ownership Ledger", "foundation", "Retain explicit commitments, decisions, owners, alternatives, due dates and completion evidence as reusable canonical records.", (1, 1, 1, 1)),
    (529, "Nexus Lifecycle Opportunity Engine", "commercial", "Relate EOL, vulnerability, lifecycle and technology-debt evidence to an accountable recommendation, design, quote, project and verified delivery path.", (1, 1, 1, 1)),
    (530, "Nexus Business Change Factory", "projects", "Turn approved acquisitions, office moves and new-site plans into governed reusable blueprints from design through cutover, verification and billing.", (1, 1, 1, 1)),
    (531, "Nexus Virtual Technician", "automation", "Give governed automation a named service identity, bounded queue, skill limits, escalation policy, workload evidence and a complete audit trail.", (1, 1, 1, 1)),
    (532, "Nexus Vertical, OEM & Embedded Platform", "ecosystem", "Package shared Nexus policies, workflows, controls and APIs for vertical editions, white-label partners and embedded use without crossing tenancy boundaries.", (1, 1, 1, 1)),
    (533, "Nexus Machine & Integration Identity", "identity", "Issue and rotate least-privilege identities for agents, Edge Nodes, connectors and automations with attestation, revocation and scoped permissions.", (1, 1, 1, 1)),
    (534, "Nexus Data & AI Boundaries", "governance", "Enforce per-tenant data-flow, residency, inference, retention and data-class controls before provider, AI or integration processing occurs.", (1, 1, 1, 1)),
    (535, "Nexus Operational Economics", "business", "Connect attributable service delivery, work, cost, risk, experience, revenue and margin to explain how the MSP can operate more effectively.", (1, 1, 1, 1)),
    (536, "Nexus Credential Lifecycle", "identity", "Orchestrate discovery, external-vault reference, approved rotation, dependency test, rollback evidence and expiry review without storing provider secrets in Nexus.", (1, 1, 1, 1)),
    (537, "Nexus Service Account Governance", "identity", "Connect service-account ownership, age, interactive-login posture, dependencies, rotation evidence and managed-identity migration plans to the accountable client.", (1, 1, 1, 1)),
    (538, "Nexus Certificate Autopilot", "security", "Discover certificate exposure, renewal dates, owners, binding targets and post-change verification; supported renewals remain approval-gated and auditable.", (1, 1, 1, 1)),
    (539, "Nexus Managed PKI", "identity", "Plan a governed private PKI for device, Wi-Fi, VPN and service identity certificates, with issuance, revocation, renewal and trust evidence.", (1, 1, 1, 1)),
    (540, "Nexus Passwordless Privileged Sessions", "identity", "Broker time-bound administrator access and remote-session credential injection through approved providers without exposing a reusable secret to technicians.", (1, 1, 1, 1)),
    (541, "Nexus Privilege & Attack Graph", "security", "Model evidence-backed privilege paths from people, devices, identities and services so the highest-impact break points can be reviewed.", (1, 1, 1, 1)),
    (542, "Nexus Deception Mesh", "security", "Deploy authorised honey signals and correlate high-confidence interactions into contained, reviewable response workflows; never present simulations as incidents.", (1, 1, 1, 1)),
    (543, "Nexus Exposure Management", "security", "Prioritise exposure through exploitability, asset criticality, reachable attack paths, compensating controls and source freshness instead of raw CVE volume.", (1, 1, 1, 1)),
    (544, "Nexus Remediation Campaigns", "security", "Stage a verified remediation across affected clients, maintenance windows, dependencies, rollback limits, approvals and outcome evidence.", (1, 1, 1, 1)),
    (545, "Nexus Security Validation", "security", "Prove approved controls through safe tests and retained evidence, explicitly distinguishing configuration, observed protection and unassessed coverage.", (1, 1, 1, 1)),
    (546, "Nexus SaaS Governance", "saas", "Discover approved and unmanaged SaaS, then relate owners, access, MFA, SSO, licence, usage and renewal evidence to the canonical client.", (1, 1, 1, 1)),
    (547, "Nexus SaaS Lifecycle", "saas", "Carry SaaS access through onboarding, role change and offboarding with provider-specific approvals, reassignment checks and audit evidence.", (1, 1, 1, 1)),
    (548, "Nexus SaaS Economics", "saas", "Identify reviewable unused licences, duplicate spend and upcoming renewals from connected provider evidence without claiming savings until approved.", (1, 1, 1, 1)),
    (549, "Nexus Contract Obligations", "commercial", "Extract and review contract dates, commitments, notice windows, service quantities and delivery obligations before creating accountable work.", (1, 1, 1, 1)),
    (550, "Nexus FinOps", "commercial", "Explain cloud and backup cost, anomalies, allocation and optimisation opportunities with declared assumptions, source data and approval boundaries.", (1, 1, 1, 1)),
    (551, "Nexus Migration Factory", "projects", "Plan, wave, verify and retain evidence for authorised data, tenant and service migrations, including cutover and rollback constraints.", (1, 1, 1, 1)),
    (552, "Nexus DNS & IPAM", "network", "Unify verified address space, DNS, DHCP, subnets, conflicts, allocation plans and discovery provenance around the client network record.", (1, 1, 1, 1)),
    (553, "Nexus Network Path Intelligence", "network", "Trace an evidence-backed route through DNS, VLANs, ACLs, firewalls and services while surfacing uncertainty and avoiding unverified topology claims.", (1, 1, 1, 1)),
    (554, "Nexus Port Intelligence", "network", "Relate switch-port state, PoE, errors, VLAN, connected device and change history to governed troubleshooting and safe network actions.", (1, 1, 1, 1)),
    (555, "Nexus Diagnostic Workspace", "operations", "Give technicians one governed, client-scoped diagnostic sequence with evidence, safe test steps, playbooks, escalation context and a reusable outcome record.", (1, 1, 1, 1)),
    (556, "Nexus Diagnostic Learning Loop", "intelligence", "Convert approved diagnostic sequences and verified outcomes into reusable playbooks while preserving authorship, scope and uncertainty.", (1, 1, 1, 1)),
    (557, "Nexus Endpoint Experience Intelligence", "endpoint", "Explain endpoint experience through observed boot, login, application, crash, storage, network and call-quality signals without reducing it to CPU alone.", (1, 1, 1, 1)),
    (558, "Nexus Slow Device Investigation", "endpoint", "Turn a reported slow device into a client-scoped, evidence-led diagnostic hypothesis with safe next checks and no automatic remediation claim.", (1, 1, 1, 1)),
    (559, "Nexus Crash Intelligence", "endpoint", "Correlate attributable application crash patterns across the authorised fleet, version, driver and device context before proposing a campaign.", (1, 1, 1, 1)),
    (560, "Nexus Boot Intelligence", "endpoint", "Separate observed boot, security, login-script and application delay so remediation starts with the actual contributor.", (1, 1, 1, 1)),
    (561, "Nexus Experience Campaigns", "endpoint", "Canary and verify approved experience improvements across affected endpoints, retaining baseline, rollout and outcome evidence.", (1, 1, 1, 1)),
    (562, "Nexus Wi-Fi Experience", "network", "Relate authorised device and access-point evidence for signal, roaming, retransmission, channel, load and authentication experience.", (1, 1, 1, 1)),
    (563, "Nexus Wi-Fi Survey", "network", "Capture site-plan, technician and access-point evidence for coverage decisions, with static alternatives where heatmap confidence is insufficient.", (1, 1, 1, 1)),
    (564, "Nexus Wi-Fi Tuning", "network", "Simulate and stage supported channel, power and steering changes with maintenance controls, verification and rollback limits.", (1, 1, 1, 1)),
    (565, "Nexus Internet Experience", "network", "Distinguish LAN, gateway, ISP, DNS, route and SaaS degradation using time-bound evidence rather than a binary WAN status.", (1, 1, 1, 1)),
    (566, "Nexus ISP Evidence Packs", "network", "Prepare an attributable, bounded carrier escalation pack from measured loss, latency, route, circuit and impacted-service evidence.", (1, 1, 1, 1)),
    (567, "Nexus Controlled Test Mesh", "network", "Coordinate rate-limited, policy-approved synthetic tests from agents and Edge Nodes without saturating customer connections.", (1, 1, 1, 1)),
    (568, "Nexus SaaS Experience", "saas", "Separate endpoint, Wi-Fi, ISP, DNS, identity, proxy and provider signals when investigating a reported SaaS experience issue.", (1, 1, 1, 1)),
    (569, "Nexus Experience Baselines", "endpoint", "Compare customer experience with its declared local baseline and source freshness, not a generic global threshold.", (1, 1, 1, 1)),
    (570, "Nexus Peripheral Intelligence", "endpoint", "Relate supported monitors, docks, headsets, scanners and printers to ownership, firmware, known issues and service history.", (1, 1, 1, 1)),
    (571, "Nexus Driver & Firmware Lifecycle", "endpoint", "Govern approved, current, problematic and rolled-back driver or firmware states through testing, staged rollout and evidence.", (1, 1, 1, 1)),
    (572, "Nexus Compatibility Campaigns", "endpoint", "Assess supported hardware and software compatibility before an upgrade, then create reviewable remediation cohorts.", (1, 1, 1, 1)),
    (573, "Nexus Employee IT App", "customer-success", "Offer employees a deliberately simple, policy-aware experience for help, device context, requests, software, access, equipment and service status.", (1, 1, 1, 1)),
    (574, "Nexus Consent-Based Support Capture", "customer-success", "Attach only user-approved device context, diagnostics, screenshots or recordings to a support request with visible consent and retention boundaries.", (1, 1, 1, 1)),
    (575, "Nexus Instant Support Consent", "remote", "Create time-bound remote-session authorisation from an employee request, preserving technician approval, scope and session evidence.", (1, 1, 1, 1)),
    (576, "Nexus Verified Self-Heal", "automation", "Offer safe user-facing remediation only after diagnosis, policy checks and verification; unsuccessful work escalates with its collected evidence.", (1, 1, 1, 1)),
    (577, "Nexus Software Service Catalogue", "service-management", "Turn approved software requests into governed policy, approval, licence, installation, verification and billing workflows.", (1, 1, 1, 1)),
    (578, "Nexus Equipment Service Catalogue", "service-management", "Carry equipment requests from approved catalogue through procurement, stock, handover, asset ownership and billing reconciliation.", (1, 1, 1, 1)),
    (579, "Nexus Joiner Mover Leaver", "identity", "Prepare governed employee lifecycle changes from declared role, manager, site and timing, with approval, dependency and completion evidence.", (1, 1, 1, 1)),
    (580, "Nexus Employee Technology Cost", "commercial", "Explain per-employee technology cost from attributable licensed services, security, equipment and declared support assumptions.", (1, 1, 1, 1)),
    (581, "Nexus Department Technology Cost", "commercial", "Aggregate attributable technology cost by declared department while exposing allocation assumptions and incomplete mappings.", (1, 1, 1, 1)),
    (582, "Nexus Secure File Exchange", "security", "Exchange sensitive files through scoped, expiring, audited and malware-scanned transfers instead of ordinary email attachments.", (1, 1, 1, 1)),
    (583, "Nexus Secret Request", "security", "Request sensitive customer information through a protected, purpose-bound flow that sends data to an approved provider without exposing it by default.", (1, 1, 1, 1)),
    (584, "Nexus Temporary Share", "security", "Publish a time-bound, authenticated and download-governed customer file share with full access evidence.", (1, 1, 1, 1)),
    (585, "Nexus Configuration File Vault", "security", "Reference encrypted, versioned configuration artefacts through least-privilege external storage or approved Nexus storage with clear key boundaries.", (1, 1, 1, 1)),
    (586, "Nexus Forms Engine", "service-management", "Build governed forms whose fields map to canonical Nexus clients, people, assets, services and approval workflows.", (1, 1, 1, 1)),
    (587, "Nexus Adaptive External Forms", "service-management", "Deliver policy-aware internal and external forms with conditional questions, secure access, validation and retained submission evidence.", (1, 1, 1, 1)),
    (588, "Nexus Agreement Signing", "commercial", "Use an appropriate external e-signature provider for legally material agreements while retaining Nexus workflow, status and evidence links.", (1, 1, 1, 1)),
    (589, "Nexus Request-First Operations", "service-management", "Make predictable employee and customer needs structured service requests, reserving tickets for incidents and exceptions while measuring zero-touch outcomes honestly.", (1, 1, 1, 1)),
    (590, "Nexus Identity Recovery", "identity", "Recover passwords, MFA and devices through verified identity, risk checks, approval, session revocation, re-enrolment and retained audit evidence.", (1, 1, 1, 1)),
    (591, "Nexus Caller Verification", "security", "Verify a customer through an approved pre-registered channel before sensitive support actions, without treating voice familiarity as proof.", (1, 1, 1, 1)),
    (592, "Nexus Technician Verification", "security", "Let a customer confirm an active technician and authorised ticket through the employee experience, reducing IT-support impersonation risk.", (1, 1, 1, 1)),
    (593, "Nexus Support Verification", "security", "Offer rotating, stronger support-verification methods with expiry and policy escalation rather than insecure static questions.", (1, 1, 1, 1)),
    (594, "Nexus Sensitive Change Authentication", "security", "Classify high-risk identity, finance, DNS and ownership changes and require independent verification before an action can proceed.", (1, 1, 1, 1)),
    (595, "Nexus Social Engineering Guard", "security", "Flag risk characteristics in requests and raise verification requirements without asserting fraud or taking an irreversible action.", (1, 1, 1, 1)),
    (596, "Nexus Fraud Response Workflow", "security", "Freeze sensitive work, preserve evidence, conduct independent verification and record release or block decisions through a governed workflow.", (1, 1, 1, 1)),
    (597, "Nexus Bare-Metal Provisioning", "endpoint", "Provision authorised hardware from signed bootstrap through assignment, OS, driver, firmware, policy, application and validation evidence.", (1, 1, 1, 1)),
    (598, "Nexus Recovery Environment", "resilience", "Provide a signed, policy-bound recovery environment for approved diagnostics, repair, data copy and reimage workflows when an agent cannot run.", (1, 1, 1, 1)),
    (599, "Nexus Rescue Media", "resilience", "Generate controlled, customer-scoped recovery media with signing, expiry, revocation and documented recovery limits.", (1, 1, 1, 1)),
    (600, "Nexus Device Replacement", "endpoint", "Plan the governed transfer of user, data, applications, identity, security, equipment and retirement evidence from old device to new.", (1, 1, 1, 1)),
    (601, "Nexus User State Migration", "endpoint", "Move authorised user profile, data and application state through a reviewable migration with verification and privacy controls.", (1, 1, 1, 1)),
    (602, "Nexus Hardware Swap", "endpoint", "Record controlled component replacement, compatibility, warranty, firmware and post-repair verification against the canonical asset.", (1, 1, 1, 1)),
    (603, "Nexus Reboot Intelligence", "endpoint", "Explain restart urgency, affected dependencies, active sessions and policy constraints before a technician or automation proposes a reboot.", (1, 1, 1, 1)),
    (604, "Nexus Reboot Coordination", "operations", "Sequence approved reboots across service dependencies with maintenance windows, customer communication and verification evidence.", (1, 1, 1, 1)),
    (605, "Nexus User Reboot Experience", "customer-success", "Give affected users clear, scheduled and defer-aware restart communication without bypassing security or maintenance policy.", (1, 1, 1, 1)),
    (606, "Nexus Patch Intelligence", "endpoint", "Prioritise patches using exposure, device role, compatibility, provider evidence, maintenance constraints and actual verification state.", (1, 1, 1, 1)),
    (607, "Nexus Patch Rings", "endpoint", "Apply approved updates through test, canary and production cohorts with versioned criteria, pause controls and rollback evidence.", (1, 1, 1, 1)),
    (608, "Nexus Patch Verification", "endpoint", "Verify installed, rebooted and healthy post-patch state rather than treating an attempted deployment as a successful patch.", (1, 1, 1, 1)),
    (609, "Nexus Emergency Patch", "endpoint", "Answer exposed-device, containment, exception and approved remediation questions quickly during a verified critical vulnerability event.", (1, 1, 1, 1)),
    (610, "Nexus App Packaging Factory", "endpoint", "Package approved applications with source, version, install, detection, dependency and rollback metadata before release.", (1, 1, 1, 1)),
    (611, "Nexus App Test Lab", "endpoint", "Test applications in representative, approved cohorts with defined success evidence before a wider deployment.", (1, 1, 1, 1)),
    (612, "Nexus App Rollback", "endpoint", "Prepare and validate a bounded rollback path before a supported application or configuration rollout is approved.", (1, 1, 1, 1)),
    (613, "Nexus App Ring Deployment", "endpoint", "Deploy approved packages through reviewable rings, pause on observed regressions and retain outcome evidence.", (1, 1, 1, 1)),
    (614, "Nexus Print Rescue", "operations", "Diagnose print failures through queue, driver, endpoint, network and device evidence, then offer safe repair packs and escalation context.", (1, 1, 1, 1)),
    (615, "Nexus Outlook Rescue", "operations", "Guide and verify approved Outlook recovery actions with relevant identity, profile, data and service evidence.", (1, 1, 1, 1)),
    (616, "Nexus Meeting Rescue", "operations", "Prioritise rapid, evidence-led recovery for Teams and meeting failures across device, network, identity and provider context.", (1, 1, 1, 1)),
    (617, "Nexus VPN Rescue", "operations", "Diagnose VPN access through client, device, certificate, MFA, route and gateway evidence with a safe escalation path.", (1, 1, 1, 1)),
    (618, "Nexus Repair Packs", "automation", "Publish versioned, approval-aware repair packs with prerequisites, simulation, verification, rollback limits and outcome history.", (1, 1, 1, 1)),
    (619, "Nexus Vendor Outage Mode", "operations", "Recognise provider-wide impact from attributable signals and switch teams into a calm, coordinated, evidence-led incident posture.", (1, 1, 1, 1)),
    (620, "Nexus Vendor Status Intelligence", "integrations", "Aggregate provider status, local evidence and historical reliability while making source freshness and disagreement visible.", (1, 1, 1, 1)),
    (621, "Nexus Status Credibility", "trust", "Explain whether an operational status is provider-reported, locally observed, inferred or unavailable so teams know how much to trust it.", (1, 1, 1, 1)),
    (622, "Nexus Customer Status Page", "customer-success", "Publish a deliberately scoped client service-status view with incidents, maintenance, subscriptions and transparent evidence boundaries.", (1, 1, 1, 1)),
    (623, "Nexus Incident Communications", "operations", "Send policy-approved, useful incident updates to affected stakeholders at configured intervals with a retained communication record.", (1, 1, 1, 1)),
    (624, "Nexus Maintenance Communications", "operations", "Identify declared affected services and stakeholders, prepare notices, confirm approvals and retain maintenance communication evidence.", (1, 1, 1, 1)),
    (625, "Nexus Change Subscriptions", "customer-success", "Let authorised stakeholders subscribe to relevant service, maintenance and incident changes without exposing unrelated customer information.", (1, 1, 1, 1)),
    (626, "Nexus IT Request Marketplace", "service-management", "Expose approved customer-requestable outcomes backed by service definitions, eligibility, approval, delivery and billing boundaries.", (1, 1, 1, 1)),
    (627, "Nexus Instant Quote", "commercial", "Prepare a reviewable quote from an approved service catalogue, agreement, quantity and cost assumptions before a customer commitment.", (1, 1, 1, 1)),
    (628, "Nexus Service Catalogue", "commercial", "Define services once with inclusions, constraints, approvals, fulfilment, billing and customer-facing language.", (1, 1, 1, 1)),
    (629, "Nexus Consumption Metering", "commercial", "Collect, normalise and reconcile authorised usage evidence for billable services while preserving source, period and confidence.", (1, 1, 1, 1)),
    (630, "Nexus Rating Engine", "commercial", "Rate connected service quantities and consumption against versioned commercial rules, never silently changing an invoice.", (1, 1, 1, 1)),
    (631, "Nexus Billing Simulation", "commercial", "Preview invoice and contract impacts from declared quantities and rate rules before approval or generation.", (1, 1, 1, 1)),
    (632, "Nexus Invoice Explain", "commercial", "Explain a generated invoice through attributable service, quantity, rate, period, adjustment and evidence records.", (1, 1, 1, 1)),
    (633, "Nexus Assurance Tests", "resilience", "Continuously and safely prove declared service outcomes with authorised tests, source evidence and clear gaps when a claim cannot be verified.", (1, 1, 1, 1)),
    (634, "Nexus Universal Clipboard", "technician-experience", "Recognise safely pasted identifiers in Nexus context, link authorised records and redact suspected secrets rather than retaining them by default.", (1, 1, 1, 1)),
    (635, "Nexus Smart Paste", "technician-experience", "Identify structured error, log and command content on paste, then offer source-backed diagnostic context without executing pasted content.", (1, 1, 1, 1)),
    (636, "Nexus Error Intelligence", "intelligence", "Connect error codes to vendor documentation, approved runbooks, client evidence and verified historical outcomes while showing source and confidence.", (1, 1, 1, 1)),
    (637, "Nexus Log Intelligence", "intelligence", "Analyse authorised logs for anomalies, timelines and meaningful healthy-baseline differences with privacy and retention controls.", (1, 1, 1, 1)),
    (638, "Nexus Cross-Device Compare", "endpoint", "Compare authorised broken and healthy devices across declared configuration dimensions, making missing and incomparable evidence explicit.", (1, 1, 1, 1)),
    (639, "Nexus Golden Device", "endpoint", "Define role-aware expected endpoint state and surface drift through evidence rather than demanding identical configuration everywhere.", (1, 1, 1, 1)),
    (640, "Nexus Known-Good State", "foundation", "Retain last verified healthy state for supported objects with source, timestamp, scope and governed restore boundaries.", (1, 1, 1, 1)),
    (641, "Nexus Before & After Evidence", "governance", "Capture appropriate pre-change and post-change state, validation and gaps automatically around authorised material changes.", (1, 1, 1, 1)),
    (642, "Nexus Technical Screenshot Timeline", "governance", "Attach strictly authorised technical-state screenshots to changes and investigations with consent, privacy, retention and access controls.", (1, 1, 1, 1)),
    (643, "Nexus Visual Diff", "governance", "Compare approved configuration screens and generated technical artefacts with human review, provenance and no claim that pixel change equals risk.", (1, 1, 1, 1)),
    (644, "Nexus Deep Discovery", "network", "Perform controlled discovery through agents, Edge Nodes and authorised connectors while respecting network scope, rate limits and client boundaries.", (1, 1, 1, 1)),
    (645, "Nexus Device Fingerprinting", "network", "Identify network devices from authorised, available evidence and retain confidence, method and conflicting observations.", (1, 1, 1, 1)),
    (646, "Nexus Rogue Device Review", "network", "Flag an unexpected device for contextual review against site, inventory, access policy and owner evidence before escalation.", (1, 1, 1, 1)),
    (647, "Nexus Network Change Detection", "network", "Detect attributable topology, address, service and configuration changes, then distinguish observed change from confirmed risk.", (1, 1, 1, 1)),
    (648, "Nexus Automatic Network Diagram", "network", "Generate reviewable topology diagrams from verified discovery and relationship evidence, with freshness and unknown paths visibly marked.", (1, 1, 1, 1)),
    (649, "Nexus Diagram Time Machine", "network", "Compare retained, evidence-backed network diagrams over time to explain what changed without inventing missing history.", (1, 1, 1, 1)),
    (650, "Nexus DNS Intelligence", "network", "Unify DNS records, registrar, provider, TLS, history, propagation and policy evidence around a client-owned domain portfolio.", (1, 1, 1, 1)),
    (651, "Nexus DNS Change Protection", "network", "Require role-appropriate verification, approval and post-change propagation evidence for sensitive DNS changes.", (1, 1, 1, 1)),
    (652, "Nexus DNS Propagation Evidence", "network", "Measure selected resolver observations with source and timing evidence rather than claiming global propagation.", (1, 1, 1, 1)),
    (653, "Nexus DNS History", "network", "Retain authorised DNS record history, approver, change source and verification outcome for accountable troubleshooting.", (1, 1, 1, 1)),
    (654, "Nexus Domain Portfolio", "network", "Manage client domain ownership, expiry, registrar, DNS, service dependency and renewal evidence as one governed portfolio.", (1, 1, 1, 1)),
    (655, "Nexus Expiry Radar", "operations", "Surface accountable dates across domains, certificates, contracts, warranties, licences and obligations with source freshness and owners.", (1, 1, 1, 1)),
    (656, "Nexus Renewal Autopilot", "commercial", "Prepare reviewable renewal work from owned renewal evidence, dependency, commercial terms and approval rules; never renew blindly.", (1, 1, 1, 1)),
    (657, "Nexus Dependency Calendar", "operations", "Expose upcoming maintenance and expiry consequences through verified service dependencies and declared business impact.", (1, 1, 1, 1)),
    (658, "Nexus Deadline Engine", "operations", "Turn explicit deadlines, notice periods, obligations and approvals into accountable work with escalation and completion evidence.", (1, 1, 1, 1)),
    (659, "Nexus Universal Notes", "collaboration", "Attach a governed note once to multiple canonical objects with audience, retention, source and audit boundaries.", (1, 1, 1, 1)),
    (660, "Nexus Smart Mentions", "collaboration", "Embed permission-filtered live object references in messages and notes without exposing out-of-scope client data.", (1, 1, 1, 1)),
    (661, "Nexus Actionable Chat", "collaboration", "Translate approved, contextual chat requests into previewable, permission-checked Nexus workflows rather than unreviewed commands.", (1, 1, 1, 1)),
    (662, "Nexus Chat Commands", "collaboration", "Offer discoverable, role-safe chat actions with clear scope, simulation and audit context.", (1, 1, 1, 1)),
    (663, "Nexus Live Incident Rooms", "operations", "Create a focused incident room with roles, timeline, evidence, customer communications, decisions and post-incident learning.", (1, 1, 1, 1)),
    (664, "Nexus Voice Notes", "collaboration", "Transcribe authorised voice notes into reviewable structured work while preserving audio consent, source and retention controls.", (1, 1, 1, 1)),
    (665, "Nexus Photo-to-Work", "onsite", "Extract reviewable asset, label and site evidence from authorised photos without presenting visual inference as confirmed inventory.", (1, 1, 1, 1)),
    (666, "Nexus Receipt Capture", "commercial", "Extract reviewable procurement and expense facts from receipts with source image, confidence and approval workflow.", (1, 1, 1, 1)),
    (667, "Nexus Expense & Mileage", "commercial", "Record attributable field expense and mileage with policy, approval, client linkage and billing boundary evidence.", (1, 1, 1, 1)),
    (668, "Nexus Field Signature", "onsite", "Capture consented field handover and completion signatures through an auditable, identity-aware workflow.", (1, 1, 1, 1)),
    (669, "Nexus Site Check-In", "onsite", "Use an authorised site check-in to surface scoped work, safety requirements, travel and onsite workflow context.", (1, 1, 1, 1)),
    (670, "Nexus Secure Disposal", "resilience", "Govern asset retirement with data-handling, custody, destruction method, evidence and customer approval requirements.", (1, 1, 1, 1)),
    (671, "Nexus Wipe Verification", "resilience", "Retain device wipe evidence and verification limits without claiming physical media destruction from a software-only signal.", (1, 1, 1, 1)),
    (672, "Nexus Sustainability", "business", "Relate declared lifecycle, reuse, power, disposal and procurement evidence to sustainability reporting with transparent assumptions.", (1, 1, 1, 1)),
    (673, "Nexus What Changed", "operations", "Answer change questions from authorised retained events, snapshots, communications and configuration evidence while clearly separating correlation from causation.", (1, 1, 1, 1)),
    (674, "Nexus Warranty & Entitlement Cloud", "commercial", "Reconcile asset entitlement, coverage, support route, expiry and claim evidence through authorised vendor sources and explicit freshness.", (1, 1, 1, 1)),
    (675, "Nexus Vendor Support Copilot", "integrations", "Prepare reviewable vendor cases from authorised diagnostics, serials, logs and history, retaining the vendor reference and disclosure boundary.", (1, 1, 1, 1)),
    (676, "Nexus Vendor Escalation Memory", "knowledge", "Preserve approved vendor escalation paths, contacts, SLA outcomes and lessons without treating anecdotal routes as universal truth.", (1, 1, 1, 1)),
    (677, "Nexus Maintenance Contract Manager", "commercial", "Track non-SaaS maintenance coverage, intervals, providers, entitlements, inspection obligations and renewal ownership.", (1, 1, 1, 1)),
    (678, "Nexus Inspection Engine", "operations", "Schedule periodic inspections with declared checklists, evidence, deficiencies, remediation ownership and verification history.", (1, 1, 1, 1)),
    (679, "Nexus Configuration Backup", "resilience", "Version supported infrastructure and SaaS configuration through authorised collection, encryption, integrity checks and source-aware retention.", (1, 1, 1, 1)),
    (680, "Nexus Configuration Recovery", "resilience", "Prepare compatible infrastructure recovery from a verified configuration snapshot with approval, dependency, validation and rollback constraints.", (1, 1, 1, 1)),
    (681, "Nexus Configuration Assurance", "security", "Compare important infrastructure state against approved expectations and surface material drift with source and verification evidence.", (1, 1, 1, 1)),
    (682, "Nexus SaaS Configuration Protection", "resilience", "Protect authorised SaaS configuration state where provider APIs permit, preserving restore limits and approval boundaries.", (1, 1, 1, 1)),
    (683, "Nexus Tenant Configuration Time Machine", "control-plane", "Compare authorised tenant state across retained snapshots with object-level provenance and gaps clearly shown.", (1, 1, 1, 1)),
    (684, "Nexus Cyber Insurance Workspace", "compliance", "Assemble insurer readiness evidence, control gaps, owners and reviewable responses without asserting cover or certification.", (1, 1, 1, 1)),
    (685, "Nexus Insurability Evidence Score", "compliance", "Show evidence-backed alignment to common insurance expectations, including unknowns and exceptions rather than a guarantee of insurability.", (1, 1, 1, 1)),
    (686, "Nexus Renewal Preparation", "commercial", "Prepare insurance and service renewals from attributable evidence, risk changes, obligations and human-approved answers.", (1, 1, 1, 1)),
    (687, "Nexus Auditor Portal", "compliance", "Provide strictly scoped, time-bound auditor access to approved evidence packs, with downloads and questions fully logged.", (1, 1, 1, 1)),
    (688, "Nexus Evidence Request", "compliance", "Gather relevant records for review before release, enforcing owner approval, redaction and an auditable disclosure trail.", (1, 1, 1, 1)),
    (689, "Nexus Audit Project", "compliance", "Coordinate audit scope, requests, evidence, findings, owners, milestones and closure verification in one accountable workspace.", (1, 1, 1, 1)),
    (690, "Nexus Policy Library", "compliance", "Version policies with owners, approval, review dates, acknowledgement, exceptions and applicable customer scope.", (1, 1, 1, 1)),
    (691, "Nexus Policy-to-Reality", "compliance", "Map approved policy requirements to observable technical and operational evidence while leaving unassessed controls visibly unassessed.", (1, 1, 1, 1)),
    (692, "Nexus Policy Drift", "compliance", "Identify when standards, systems or processes diverge and propose an accountable review rather than silently changing a control.", (1, 1, 1, 1)),
    (693, "Nexus Business Continuity Manager", "resilience", "Maintain approved continuity plans, contacts, dependencies, recovery priorities, exercises and evidence around customer services.", (1, 1, 1, 1)),
    (694, "Nexus Continuity Test", "resilience", "Plan and verify authorised continuity exercises with test scope, observed results, gaps, decisions and remediation ownership.", (1, 1, 1, 1)),
    (695, "Nexus Dependency Risk", "relationships", "Explain shared-service, supplier and configuration dependency risk with source records and explicit uncertainty.", (1, 1, 1, 1)),
    (696, "Nexus Technician Departure", "team", "Govern staff offboarding through access, ownership, active work, knowledge transfer, device and customer-responsibility evidence.", (1, 1, 1, 1)),
    (697, "Nexus Knowledge Coverage", "knowledge", "Measure verified documentation coverage for customer, service, asset and operational ownership without rewarding empty pages.", (1, 1, 1, 1)),
    (698, "Nexus Succession Readiness", "team", "Surface unowned services, key-person knowledge and handover gaps before a technician or vendor departure becomes an incident.", (1, 1, 1, 1)),
    (699, "Nexus Hiring Planner", "business", "Model staffing demand from attributable workload, skills, coverage, service commitments and assumptions for accountable hiring plans.", (1, 1, 1, 1)),
    (700, "Nexus Skill Gap Intelligence", "team", "Relate declared service needs and approved training evidence to technician skill coverage without making unsupported performance claims.", (1, 1, 1, 1)),
    (701, "Nexus Training ROI", "team", "Connect training investment to declared skills, service coverage and outcome evidence while keeping causal claims conservative.", (1, 1, 1, 1)),
    (702, "Nexus Autonomous NOC", "automation", "Run bounded, policy-approved operational detection and remediation with confidence, escalation, simulation and complete audit evidence.", (1, 1, 1, 1)),
    (703, "Nexus Autonomous SOC", "security", "Perform bounded, human-governed triage and containment preparation from verified security signals without autonomous destructive response by default.", (1, 1, 1, 1)),
    (704, "Nexus Autonomous Service Desk", "automation", "Resolve eligible predictable requests through approved runbooks, identity controls and verification before escalating with context.", (1, 1, 1, 1)),
    (705, "Nexus After-Hours Operations", "operations", "Apply approved overnight handling for known safe cases with customer policy, escalation, evidence and next-business-day review.", (1, 1, 1, 1)),
    (706, "Nexus Overflow Coordination", "operations", "Detect capacity and SLA pressure, then route authorised work to approved overflow capacity with customer and data-boundary controls.", (1, 1, 1, 1)),
    (707, "Nexus Specialist Exchange", "ecosystem", "Connect approved specialist capability to a scoped engagement, competency evidence and accountable handover without exposing unrelated client data.", (1, 1, 1, 1)),
    (708, "Nexus MSP-to-MSP Collaboration", "ecosystem", "Coordinate deliberately authorised cross-MSP work through isolated scopes, contracts, audit trails and shared outcome evidence.", (1, 1, 1, 1)),
    (709, "Nexus Service Ownership Federation", "relationships", "Model which MSP, vendor, client team or specialist owns each service boundary and how escalation should proceed.", (1, 1, 1, 1)),
    (710, "Nexus Co-Managed IT", "customer-success", "Support shared client and MSP responsibilities through explicit permissions, task ownership, evidence and clear handover states.", (1, 1, 1, 1)),
    (711, "Nexus Responsibility Matrix", "relationships", "Maintain accountable responsibility matrices linking service, task, decision, owner, approver and escalation route.", (1, 1, 1, 1)),
    (712, "Nexus Who Owns This", "relationships", "Answer ownership questions by traversing authorised service, provider, contract and responsibility records with evidence links.", (1, 1, 1, 1)),
    (713, "Nexus Change Impact Explorer", "relationships", "Preview the likely affected dependencies, controls, customers and rollback limits before a material change is approved.", (1, 1, 1, 1)),
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _seed_document(number: int, title: str, category: str, summary: str, axes: tuple[int, int, int, int], source_number: int | None = None) -> dict[str, Any]:
    source = (
        "vendor-assurance-autonomy-federation-brief-674-713" if number >= 674
        else "technician-network-field-brief-634-673" if number >= 634
        else "identity-recovery-resilience-billing-brief-590-633" if number >= 590
        else "experience-requests-services-brief-557-589" if number >= 557
        else "security-saas-diagnostics-brief-536-556" if number >= 536
        else "enterprise-operating-intelligence-brief-526-535" if number >= 526
        else "platform-horizon-brief-512-525" if number >= 512
        else "category-platform-brief-499-511" if number >= 499
        else "control-plane-master-roadmap-487-498" if number >= 487
        else "interaction-delight-brief-401-430" if number >= 457
        else "purposeful-motion-brief-401-445" if source_number and source_number >= 401
        else "experience-design-brief-371-400" if source_number and source_number >= 371
        else "self-improving-platform-brief-351-370" if source_number
        else "product-architect-brief-326-350"
    )
    return {
        "id": f"idea-{number}",
        "number": number,
        "title": title,
        "category": category,
        "summary": summary,
        "status": "captured",
        "horizon": "explore",
        "source": source,
        "source_number": source_number or number,
        "value_axes": dict(zip(VALUE_AXES, (bool(value) for value in axes))),
        "evidence": [],
        "dependencies": ["core-platform"],
        "decision_note": None,
        "created_at": _now(),
        "updated_at": _now(),
    }


async def ensure_idea_catalog() -> None:
    for idea in (_seed_document(*row) for row in _IDEAS):
        await db.nexus_ideas.update_one({"id": idea["id"]}, {"$setOnInsert": idea}, upsert=True)
    await db.nexus_ideas.create_index("id", unique=True)
    await db.nexus_ideas.create_index([("status", 1), ("number", 1)])


async def ideas_snapshot() -> dict[str, Any]:
    await ensure_idea_catalog()
    ideas = await db.nexus_ideas.find({}, {"_id": 0}).sort([("number", 1), ("created_at", 1)]).to_list(1000)
    status_counts = Counter(str(item.get("status") or "captured") for item in ideas)
    axis_counts = {
        axis: sum(1 for item in ideas if (item.get("value_axes") or {}).get(axis))
        for axis in VALUE_AXES
    }
    return {
        "name": "Nexus Ideas",
        "items": ideas,
        "statuses": list(IDEA_STATUSES),
        "value_axes": list(VALUE_AXES),
        "summary": {"total": len(ideas), "status_counts": dict(status_counts), "axis_counts": axis_counts},
        "policy": [
            "Captured is not approved, scheduled, or released.",
            "Every idea must save time, reduce stress, increase confidence, or create opportunity.",
            "Promotion to the roadmap requires dependencies, evidence, an owner, and a release gate.",
            "Rejected and parked ideas remain retained so product decisions are not forgotten.",
        ],
    }


async def create_idea(payload: dict[str, Any], actor: dict[str, Any]) -> dict[str, Any]:
    axes = {axis: bool((payload.get("value_axes") or {}).get(axis)) for axis in VALUE_AXES}
    if not any(axes.values()):
        raise ValueError("Select at least one Nexus value principle")
    now = _now()
    idea = {
        "id": f"idea-{uuid.uuid4()}",
        "number": None,
        "title": str(payload.get("title") or "").strip(),
        "category": str(payload.get("category") or "general").strip().lower(),
        "summary": str(payload.get("summary") or "").strip(),
        "status": "captured",
        "horizon": str(payload.get("horizon") or "explore").strip().lower(),
        "source": "nexus-foundation",
        "value_axes": axes,
        "evidence": [],
        "dependencies": payload.get("dependencies") or ["core-platform"],
        "decision_note": None,
        "created_by": actor.get("id"),
        "created_by_name": actor.get("name") or actor.get("email"),
        "created_at": now,
        "updated_at": now,
    }
    await db.nexus_ideas.insert_one(dict(idea))
    return idea


async def update_idea(idea_id: str, payload: dict[str, Any], actor: dict[str, Any]) -> dict[str, Any] | None:
    allowed = {"status", "horizon", "decision_note", "category", "summary", "dependencies", "value_axes"}
    update = {key: value for key, value in payload.items() if key in allowed and value is not None}
    if "status" in update and update["status"] not in IDEA_STATUSES:
        raise ValueError("Unsupported idea status")
    if "value_axes" in update:
        update["value_axes"] = {axis: bool(update["value_axes"].get(axis)) for axis in VALUE_AXES}
        if not any(update["value_axes"].values()):
            raise ValueError("Select at least one Nexus value principle")
    update.update({"updated_at": _now(), "updated_by": actor.get("id"), "updated_by_name": actor.get("name") or actor.get("email")})
    result = await db.nexus_ideas.update_one({"id": idea_id}, {"$set": update})
    if not result.matched_count:
        return None
    return await db.nexus_ideas.find_one({"id": idea_id}, {"_id": 0})
