import {
  LayoutDashboard, Ticket, Monitor, Package, Users, FileText,
  Receipt, Clock, BookOpen, Cloud, Network, Laptop, BarChart3,
  Settings, Zap, UserPlus, Shield, Mail, Terminal, Key,
  FolderKanban, Server, CalendarClock, UserCog, CalendarDays,
  ShoppingCart, Wifi, Trophy, Phone, Building2, Tags, ShieldCheck,
  Activity, CreditCard, Bell, Cpu, Heart, Wrench, Radar,
  Paintbrush, Gift, Volume2, DollarSign, Wallet, Navigation, Bot,
  KeyRound, QrCode, Workflow, Timer, ScanLine, TrendingUp,
  FileBarChart, History, ShieldAlert, Target, MapPin, Map, Award,
  CheckSquare, RefreshCw, FileSearch, Star, BarChart, Calculator,
  TrendingDown, GitBranch, Flame, MessageSquare, HardDrive,
  ShoppingBag, Globe, PatchCheck, Lock, BellOff, Layers,
  Gauge, WifiIcon, Eye, Bug, FileWarning, ClipboardList, Kanban,
  Search, BrainCircuit, TestTube, Crosshair, ThumbsUp, MapPinned,
  HeartPulse, AlertTriangle, Banknote, MessageCircle,
  FileSpreadsheet, Fingerprint, Webhook, GitMerge, BadgeDollarSign, Swords,
  LayoutGrid, Building, Smartphone, Radio, Coins
} from "lucide-react";

export const navGroups = [
  {
    title: "Main",
    items: [
      { path: "/", icon: LayoutDashboard, label: "Dashboard" },
      { path: "/tickets", icon: Ticket, label: "Tickets" },
      { path: "/kanban-tickets", icon: FolderKanban, label: "Kanban Board" },
      { path: "/sla-timer", icon: Timer, label: "SLA Timer" },
      { path: "/sla-penalties", icon: Calculator, label: "SLA Penalties" },
      { path: "/dispatch-board", icon: MapPin, label: "Dispatch Board" },
      { path: "/escalation-matrix", icon: Bell, label: "Escalation Matrix" },
      { path: "/change-management", icon: GitBranch, label: "Change Mgmt" },
      { path: "/incident-heatmap", icon: Flame, label: "Incident Heatmap" },
      { path: "/technicians", icon: UserCog, label: "Technicians" },
      { path: "/skills-matrix", icon: Award, label: "Skills Matrix" },
      { path: "/tech-utilization", icon: Clock, label: "Tech Utilization" },
      { path: "/leaderboard", icon: Trophy, label: "Leaderboard" },
      { path: "/scheduling", icon: CalendarDays, label: "Scheduling" },
      { path: "/smart-scheduling", icon: Navigation, label: "Smart Routing" },
      { path: "/mobile-tech", icon: Smartphone, label: "Mobile Tech" },
      { path: "/wallboard", icon: Monitor, label: "NOC Wallboard" },
      { path: "/approvals", icon: CheckSquare, label: "Approvals" },
      { path: "/postmortem", icon: FileSearch, label: "Post-Mortems" },
      { path: "/live-chat", icon: MessageSquare, label: "Live Chat" },
      { path: "/custom-monitors", icon: Activity, label: "Custom Monitors" },
      { path: "/script-ticket", icon: Terminal, label: "Script-to-Ticket" },
      { path: "/alert-suppression", icon: BellOff, label: "Alert Suppression" },
      { path: "/maintenance-scheduler", icon: CalendarClock, label: "Maintenance" },
    ]
  },
  {
    title: "Infrastructure",
    items: [
      { path: "/devices", icon: Monitor, label: "Devices" },
      { path: "/bulk-actions", icon: Zap, label: "Bulk Actions" },
      { path: "/topology", icon: Wifi, label: "Network Topology" },
      { path: "/networking", icon: Wifi, label: "Networking" },
      { path: "/dns-monitor", icon: Globe, label: "DNS Monitor" },
      { path: "/bandwidth-monitor", icon: Gauge, label: "Bandwidth" },
      { path: "/dmarc-compliance", icon: ShieldCheck, label: "Email Security" },
      { path: "/splynx-dashboard", icon: Activity, label: "ISP Health" },
      { path: "/assets", icon: Package, label: "Assets" },
      { path: "/qr-assets", icon: QrCode, label: "QR Asset Tags" },
      { path: "/asset-lifecycle", icon: Wrench, label: "Asset Lifecycle" },
      { path: "/asset-depreciation", icon: RefreshCw, label: "Depreciation" },
      { path: "/warranty-tracker", icon: Shield, label: "Warranty Tracker" },
      { path: "/backup-compliance", icon: HardDrive, label: "Backup Compliance" },
      { path: "/backup-dashboard", icon: HardDrive, label: "Backup Dashboard" },
      { path: "/patch-compliance", icon: ShieldCheck, label: "Patch Compliance" },
      { path: "/procurement-planner", icon: ShoppingBag, label: "Procurement" },
      { path: "/predictive-maintenance", icon: Cpu, label: "Predictive AI" },
      { path: "/doc-scanner", icon: ScanLine, label: "Document Scanner" },
      { path: "/vault", icon: KeyRound, label: "Password Vault" },
      { path: "/runbooks", icon: Workflow, label: "Runbook Automation" },
      { path: "/scripting", icon: Terminal, label: "Scripting" },
      { path: "/remote-access", icon: Laptop, label: "Remote Access" },
    ]
  },
  {
    title: "Business",
    items: [
      { path: "/clients", icon: Users, label: "Clients" },
      { path: "/client-health", icon: Activity, label: "Client Health" },
      { path: "/client-timeline", icon: History, label: "Client Timeline" },
      { path: "/client-compare", icon: BarChart, label: "Client Compare" },
      { path: "/client-risk", icon: ShieldAlert, label: "Client Risk" },
      { path: "/csat-surveys", icon: Star, label: "CSAT Surveys" },
      { path: "/client-reports", icon: FileText, label: "Client Reports" },
      { path: "/sla-report-gen", icon: FileBarChart, label: "Client SLA Reports" },
      { path: "/client-portal-admin", icon: Users, label: "Client Portal" },
      { path: "/onboarding", icon: Zap, label: "Client Onboarding" },
      { path: "/sentiment", icon: Heart, label: "Client Sentiment" },
      { path: "/it-roadmap", icon: Map, label: "IT Roadmap" },
      { path: "/upsell", icon: TrendingUp, label: "Upsell Detector" },
      { path: "/revenue-forecast", icon: TrendingUp, label: "Revenue Forecast" },
      { path: "/rpe-dashboard", icon: Target, label: "Revenue/Endpoint" },
      { path: "/contract-profit", icon: DollarSign, label: "Contract Profit" },
      { path: "/profitability-heatmap", icon: BarChart3, label: "Profitability Map" },
      { path: "/cost-per-ticket", icon: DollarSign, label: "Cost/Ticket" },
      { path: "/roi-reports", icon: FileBarChart, label: "ROI Reports" },
      { path: "/leads", icon: UserPlus, label: "Leads & CRM" },
      { path: "/loyalty", icon: Gift, label: "Loyalty & Renewals" },
      { path: "/campaigns", icon: Mail, label: "Email Campaigns" },
      { path: "/products", icon: Package, label: "Products" },
      { path: "/purchase-orders", icon: ShoppingCart, label: "Purchase Orders" },
      { path: "/stocktake", icon: Package, label: "Stocktake" },
      { path: "/vendors", icon: Building2, label: "Vendors" },
      { path: "/vendor-scorecard", icon: Star, label: "Vendor Scorecard" },
      { path: "/rentals", icon: Phone, label: "Phone Rentals" },
      { path: "/projects", icon: FolderKanban, label: "Projects" },
      { path: "/contracts", icon: FileText, label: "Contracts" },
      { path: "/invoices", icon: Receipt, label: "Invoices" },
      { path: "/estimates", icon: FileText, label: "Estimates" },
      { path: "/recurring-invoices", icon: RefreshCw, label: "Recurring Invoices" },
      { path: "/billing-recon", icon: DollarSign, label: "Billing Recon" },
      { path: "/xero", icon: CreditCard, label: "Xero Accounting" },
      { path: "/time-tracking", icon: Clock, label: "Time Tracking" },
      { path: "/license-management", icon: Layers, label: "License Mgmt" },
      { path: "/usage-billing", icon: Receipt, label: "Usage Billing" },
      { path: "/pricing-calc", icon: Banknote, label: "Pricing Calculator" },
      { path: "/late-payment", icon: BadgeDollarSign, label: "Late Payment AI" },
      { path: "/qbr-generator", icon: FileSpreadsheet, label: "QBR Generator" },
      { path: "/revenue-tracker", icon: Coins, label: "Revenue Tracker" },
    ]
  },
  {
    title: "Communication",
    items: [
      { path: "/email", icon: Mail, label: "Email" },
      { path: "/o365-setup", icon: Mail, label: "O365 Mailbox" },
      { path: "/comms-timeline", icon: MessageCircle, label: "Comms Timeline" },
      { path: "/documentation", icon: Key, label: "IT Docs" },
      { path: "/capacity-planner", icon: Users, label: "Capacity Planner" },
      { path: "/auto-documentation", icon: FileText, label: "Auto-Docs" },
      { path: "/knowledge-base", icon: BookOpen, label: "Knowledge Base" },
    ]
  },
  {
    title: "Security Operations",
    items: [
      { path: "/security-dashboard", icon: Shield, label: "Security SOC" },
      { path: "/endpoint-security", icon: ShieldCheck, label: "Endpoint Scores" },
      { path: "/threat-timeline", icon: Flame, label: "Threat Timeline" },
      { path: "/identity-threats", icon: Eye, label: "Identity Threats" },
      { path: "/ransomware-canary", icon: FileWarning, label: "Ransomware Canary" },
      { path: "/remediation-playbooks", icon: Workflow, label: "Remediation" },
      { path: "/soc-feed", icon: Activity, label: "SOC Feed" },
      { path: "/vulnerability-scanner", icon: Bug, label: "Vuln Scanner" },
      { path: "/third-party-patching", icon: ShieldCheck, label: "3rd Party Patches" },
      { path: "/audit-trail", icon: ClipboardList, label: "Audit Trail" },
      { path: "/zero-trust", icon: Fingerprint, label: "Zero Trust" },
      { path: "/ransomware-tabletop", icon: Swords, label: "Ransomware Tabletop" },
      { path: "/soc-realtime", icon: Radio, label: "Live SOC Feed" },
    ]
  },
  {
    title: "Security & Compliance",
    items: [
      { path: "/compliance", icon: ShieldAlert, label: "Compliance Reports" },
      { path: "/compliance-report-gen", icon: FileText, label: "Compliance Gen" },
      { path: "/mfa-management", icon: Lock, label: "MFA Management" },
      { path: "/password-rotation", icon: RefreshCw, label: "Password Rotation" },
    ]
  },
  {
    title: "Integrations",
    items: [
      { path: "/proxmox", icon: Server, label: "Proxmox" },
      { path: "/domotz", icon: Network, label: "Domotz" },
      { path: "/acronis", icon: Shield, label: "Acronis" },
      { path: "/pax8", icon: Cloud, label: "Pax8" },
      { path: "/gradient", icon: DollarSign, label: "Gradient MSP" },
      { path: "/webhook-builder", icon: Webhook, label: "Webhook Builder" },
      { path: "/git-scripts", icon: GitMerge, label: "Git Scripts Sync" },
      { path: "/channel-mode", icon: Building, label: "Channel / MSP Mode" },
    ]
  },
  {
    title: "AI & Intelligence",
    items: [
      { path: "/nlp-query", icon: Search, label: "NLP Search" },
      { path: "/ai-resolution", icon: BrainCircuit, label: "AI Auto-Resolve" },
      { path: "/patch-hub", icon: Layers, label: "Patch Hub" },
      { path: "/self-healing", icon: HeartPulse, label: "AI Self-Healing" },
      { path: "/predictive-failure", icon: AlertTriangle, label: "Predictive Failure" },
      { path: "/dashboard-builder", icon: LayoutGrid, label: "Dashboard Builder" },
    ]
  },
  {
    title: "System",
    items: [
      { path: "/health-radar", icon: Radar, label: "Health Radar" },
      { path: "/benchmarking", icon: BarChart3, label: "Benchmarking" },
      { path: "/white-label", icon: Paintbrush, label: "White Label" },
      { path: "/expiry-tracker", icon: CalendarClock, label: "Expiry Tracker" },
      { path: "/executive-reports", icon: FileBarChart, label: "Exec Reports" },
      { path: "/nps-tracker", icon: ThumbsUp, label: "NPS Tracker" },
      { path: "/client-budget", icon: DollarSign, label: "Client Budgets" },
      { path: "/geo-map", icon: MapPinned, label: "Geo Map" },
      { path: "/onboarding-workflows", icon: ClipboardList, label: "Onboarding" },
      { path: "/hardware-refresh", icon: HardDrive, label: "HW Refresh" },
      { path: "/dark-web-monitor", icon: Eye, label: "Dark Web Monitor" },
      { path: "/phishing-sim", icon: Crosshair, label: "Phishing Sim" },
      { path: "/backup-verify", icon: TestTube, label: "Backup Verify" },
      { path: "/compliance-frameworks", icon: Shield, label: "Compliance" },
      { path: "/reports", icon: BarChart3, label: "Reports" },
      { path: "/financial-reports", icon: Wallet, label: "Financial Reports" },
      { path: "/ticket-settings", icon: Tags, label: "Ticket Settings" },
      { path: "/ticket-ping-settings", icon: Volume2, label: "Ping & Escalation" },
      { path: "/settings", icon: Settings, label: "Settings" },
    ]
  },
];
