import {
  Activity,
  BadgeCheck,
  Bot,
  Boxes,
  CloudCog,
  Coins,
  DatabaseBackup,
  FolderKanban,
  Gauge,
  KeyRound,
  Lightbulb,
  Network,
  PackageOpen,
  Phone,
  Radar,
  Receipt,
  Rocket,
  ShieldCheck,
  Store,
} from "lucide-react";

/**
 * The public Nexus product taxonomy.
 *
 * Existing routes remain the compatibility contract. Product names can evolve
 * without forcing a risky route, API, or database rename across the platform.
 * Vault and Verify deliberately orchestrate approved providers instead of
 * becoming duplicate password or MFA stores.
 */
export const NEXUS_PRODUCTS = [
  {
    id: "nexusmsp",
    name: "NexusMSP",
    strapline: "The MSP operating system",
    description: "Clients, service delivery, onboarding, contracts, billing, collaboration and one auditable operational record.",
    route: "/",
    category: "Core platform",
    icon: Boxes,
    tone: "cyan",
    delivery: "native",
    capabilities: ["Service desk", "Client 360", "Operational timeline"],
  },
  {
    id: "control",
    name: "Nexus Control",
    strapline: "Cloud and tenant control plane",
    description: "Microsoft 365, identity, Exchange, Intune, Defender, licensing and cross-platform operational search.",
    route: "/control-plane",
    category: "Control & intelligence",
    icon: CloudCog,
    tone: "sky",
    delivery: "native",
    capabilities: ["Microsoft 365", "Tenant operations", "Universal search"],
  },
  {
    id: "shield",
    name: "Nexus Shield",
    strapline: "Endpoint protection and response",
    description: "Endpoint posture, Nexus Canary, vulnerability evidence, remediation and controlled privilege workflows.",
    route: "/nexus-shield",
    category: "Security & trust",
    icon: ShieldCheck,
    tone: "emerald",
    delivery: "native",
    capabilities: ["Endpoint posture", "Nexus Canary", "Remediation"],
  },
  {
    id: "backup",
    name: "Nexus Backup",
    strapline: "Backup posture and recovery assurance",
    description: "Protection coverage, restore verification, compliance evidence, billing alignment and recovery readiness.",
    route: "/backup-center",
    category: "Infrastructure",
    icon: DatabaseBackup,
    tone: "emerald",
    delivery: "native",
    capabilities: ["Protection coverage", "Restore tests", "Billing evidence"],
  },
  {
    id: "remote",
    name: "Nexus Remote",
    strapline: "Audited remote support",
    description: "Technician-initiated support sessions with device context, customer consent, provider policy and activity history.",
    route: "/remote-access",
    category: "Infrastructure",
    icon: Radar,
    tone: "sky",
    delivery: "native",
    capabilities: ["Remote sessions", "Consent", "Session audit"],
  },
  {
    id: "voice",
    name: "Nexus Voice",
    strapline: "PBX and extension operations",
    description: "Yeastar PBXs, extensions, customer mappings, synchronisation history and agreement-based extension billing.",
    route: "/voice",
    category: "Infrastructure",
    icon: Phone,
    tone: "violet",
    delivery: "native",
    capabilities: ["Yeastar PBXs", "Extensions", "Billing sync"],
  },
  {
    id: "telecom",
    name: "Nexus Telecom",
    strapline: "Usage-led service billing",
    description: "Usage, quantities, plan evidence and recurring commercial alignment for telecom and metered services.",
    route: "/usage-billing",
    category: "Infrastructure",
    icon: Activity,
    tone: "cyan",
    delivery: "native",
    capabilities: ["Usage records", "Plan quantities", "Recurring billing"],
  },
  {
    id: "monitor",
    name: "Nexus Monitor",
    strapline: "Managed endpoint observability",
    description: "Live device health, signals, software, compliance, maintenance and technician actions from the Nexus Agent.",
    route: "/devices",
    category: "Infrastructure",
    icon: Gauge,
    tone: "cyan",
    delivery: "native",
    capabilities: ["Device health", "Signals", "Agent actions"],
  },
  {
    id: "deploy",
    name: "Nexus Deploy",
    strapline: "Software, patch and automation delivery",
    description: "Patch orchestration, script packs, application delivery, maintenance windows and accountable rollout history.",
    route: "/automation-hub",
    category: "Infrastructure",
    icon: Rocket,
    tone: "amber",
    delivery: "native",
    capabilities: ["Patch delivery", "Script packs", "Runbooks"],
  },
  {
    id: "network",
    name: "Nexus Network",
    strapline: "Network operations and topology",
    description: "Sites, topology, bandwidth, infrastructure discovery and provider-backed network management.",
    route: "/networking",
    category: "Infrastructure",
    icon: Network,
    tone: "sky",
    delivery: "native",
    capabilities: ["Topology", "Sites", "Network health"],
  },
  {
    id: "dns",
    name: "Nexus DNS",
    strapline: "Domain and DNS assurance",
    description: "Domain monitoring, DNS checks, change history, certificate awareness and actionable service alerts.",
    route: "/dns-monitor",
    category: "Infrastructure",
    icon: Activity,
    tone: "violet",
    delivery: "native",
    capabilities: ["DNS health", "Domains", "Change history"],
  },
  {
    id: "vault",
    name: "Nexus Vault",
    strapline: "Provider-backed secret context",
    description: "Securely routes technicians to Keeper and approved Hudu records without duplicating passwords inside NexusMSP.",
    route: "/hudu",
    category: "Security & trust",
    icon: KeyRound,
    tone: "amber",
    delivery: "provider",
    capabilities: ["Keeper references", "Hudu context", "Access audit"],
    boundary: "NexusMSP does not store a second password vault.",
  },
  {
    id: "verify",
    name: "Nexus Verify",
    strapline: "Microsoft-backed identity assurance",
    description: "Identity posture, MFA coverage, conditional access evidence and reviewed actions through Microsoft.",
    route: "/control-plane?module=microsoft365&view=security",
    category: "Security & trust",
    icon: BadgeCheck,
    tone: "emerald",
    delivery: "provider",
    capabilities: ["MFA posture", "Conditional access", "Identity evidence"],
    boundary: "Microsoft remains the MFA and identity source of truth.",
  },
  {
    id: "projects",
    name: "Nexus Projects",
    strapline: "Structured delivery management",
    description: "Milestones, assignments, client visibility, financial context and accountable delivery from scope to handover.",
    route: "/projects",
    category: "Business operations",
    icon: FolderKanban,
    tone: "violet",
    delivery: "native",
    capabilities: ["Milestones", "Delivery work", "Client visibility"],
  },
  {
    id: "finance",
    name: "Nexus Finance",
    strapline: "Commercial operations",
    description: "Invoices, recurring billing, purchasing, contract alignment, reconciliation and finance-ready audit evidence.",
    route: "/billing-dashboard",
    category: "Business operations",
    icon: Receipt,
    tone: "emerald",
    delivery: "native",
    capabilities: ["Invoices", "Recurring billing", "Reconciliation"],
  },
  {
    id: "insight",
    name: "Nexus Insight",
    strapline: "Operational and business intelligence",
    description: "Client trajectories, risk, predictive signals, compliance evidence and decision-ready reporting.",
    route: "/insights",
    category: "Control & intelligence",
    icon: Lightbulb,
    tone: "amber",
    delivery: "native",
    capabilities: ["Predictive signals", "Client trends", "Risk evidence"],
  },
  {
    id: "ai",
    name: "Nexus AI",
    strapline: "Technician-approved intelligence",
    description: "Triage, recommendations, documentation, simulation and explainable assistance across the Nexus platform.",
    route: "/auto-ops",
    category: "Control & intelligence",
    icon: Bot,
    tone: "violet",
    delivery: "native",
    capabilities: ["AI triage", "Recommendations", "Simulation"],
  },
  {
    id: "store",
    name: "Nexus Store",
    strapline: "Connectors and automation packs",
    description: "A governed catalogue of integrations, automation packs, scripts and reusable operational capabilities.",
    route: "/nexus-suite?view=store",
    category: "Control & intelligence",
    icon: Store,
    tone: "cyan",
    delivery: "native",
    capabilities: ["Integrations", "Automation packs", "Script library"],
  },
];
export const NEXUS_PRODUCT_CATEGORIES = [
  "All products",
  "Core platform",
  "Control & intelligence",
  "Security & trust",
  "Infrastructure",
  "Business operations",
];

export const NEXUS_STORE_COLLECTIONS = [
  {
    id: "connectors",
    title: "Connected providers",
    description: "Configure and validate the services that provide evidence and actions to NexusMSP.",
    route: "/integrations",
    icon: PackageOpen,
    tone: "cyan",
  },
  {
    id: "automation",
    title: "Automation marketplace",
    description: "Install governed workflow packs with simulation, approvals, rollback and change evidence.",
    route: "/workflow-automation?tab=marketplace",
    icon: Rocket,
    tone: "violet",
  },
  {
    id: "scripts",
    title: "Technician script library",
    description: "Discover, install and maintain approved diagnostic and remediation script packs.",
    route: "/scripting?tab=library",
    icon: PackageOpen,
    tone: "amber",
  },
  {
    id: "commercial",
    title: "Products and services",
    description: "Maintain the commercial catalogue used by quotes, contracts, invoices and recurring services.",
    route: "/products",
    icon: Coins,
    tone: "emerald",
  },
];
