import { useState, useEffect } from "react";
import axios from "axios";
import { API, useAuth } from "@/App";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FileText, Zap, Users, Mail } from "lucide-react";
import { toast } from "sonner";

export default function ClientReportsPage() {
  const { token } = useAuth();
  const [clients, setClients] = useState([]);
  const [selectedClient, setSelectedClient] = useState("");
  const [templates, setTemplates] = useState([]);
  const [history, setHistory] = useState([]);
  const [currentReport, setCurrentReport] = useState(null);
  const [generating, setGenerating] = useState(false);
  const headers = { Authorization: `Bearer ${token}` };

  useEffect(() => {
    Promise.all([
      axios.get(`${API}/clients`, { headers }),
      axios.get(`${API}/client-reports/templates`, { headers }),
      axios.get(`${API}/client-reports/history`, { headers }),
    ]).then(([c, t, h]) => { setClients(c.data); setTemplates(t.data); setHistory(h.data); }).catch(() => {});
  }, []);

  const generate = async () => {
    if (!selectedClient) { toast.error("Select a client"); return; }
    setGenerating(true);
    try {
      const { data } = await axios.get(`${API}/client-reports/generate/${selectedClient}`, { headers });
      setCurrentReport(data);
      setHistory(prev => [data, ...prev]);
      toast.success("Report generated");
    } catch { toast.error("Failed"); }
    setGenerating(false);
  };

  return (
    <div className="space-y-6" data-testid="client-reports-page">
      <div className="flex items-center justify-between">
        <div><h1 className="text-2xl font-bold tracking-tight">Automated Client Reports</h1>
          <p className="text-muted-foreground text-sm mt-1">Generate and schedule reports for clients</p></div>
        <div className="flex gap-3 items-center">
          <Select value={selectedClient} onValueChange={setSelectedClient}>
            <SelectTrigger className="w-[240px]" data-testid="report-client-select"><SelectValue placeholder="Select client..." /></SelectTrigger>
            <SelectContent>{clients.map(c => <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent>
          </Select>
          <Button onClick={generate} disabled={generating} data-testid="generate-report">
            <Zap className={`w-4 h-4 mr-2 ${generating ? "animate-spin" : ""}`} />{generating ? "Generating..." : "Generate Report"}
          </Button>
        </div>
      </div>

      {currentReport && (
        <Card className="border-2 border-primary/30">
          <CardHeader><CardTitle className="text-base flex items-center gap-2"><FileText className="w-4 h-4" />{currentReport.client_name} - {currentReport.period}</CardTitle></CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="p-3 bg-muted/50 rounded-lg"><p className="text-xs text-muted-foreground mb-1">Tickets</p>
                <p className="text-lg font-bold">{currentReport.sections.tickets.total}</p>
                <p className="text-xs">Open: {currentReport.sections.tickets.open} | Resolved: {currentReport.sections.tickets.resolved}</p>
                <p className="text-xs text-green-500">{currentReport.sections.tickets.resolution_rate}% resolution</p></div>
              <div className="p-3 bg-muted/50 rounded-lg"><p className="text-xs text-muted-foreground mb-1">Devices</p>
                <p className="text-lg font-bold">{currentReport.sections.devices.total}</p>
                <p className="text-xs">Online: {currentReport.sections.devices.online} | Offline: {currentReport.sections.devices.offline}</p>
                <p className="text-xs">Compliance: {currentReport.sections.devices.avg_compliance}%</p></div>
              <div className="p-3 bg-muted/50 rounded-lg"><p className="text-xs text-muted-foreground mb-1">Financial</p>
                <p className="text-lg font-bold">${currentReport.sections.financial.mrr.toLocaleString()}/mo</p>
                <p className="text-xs">{currentReport.sections.financial.contracts} contracts</p></div>
              <div className="p-3 bg-muted/50 rounded-lg"><p className="text-xs text-muted-foreground mb-1">Satisfaction</p>
                <p className="text-lg font-bold">{currentReport.sections.satisfaction.avg_csat}/5</p>
                <p className="text-xs">{currentReport.sections.satisfaction.responses} responses</p></div>
            </div>
            <p className="text-xs text-muted-foreground mt-3">Generated by {currentReport.generated_by} on {new Date(currentReport.generated_at).toLocaleString()}</p>
          </CardContent>
        </Card>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader><CardTitle className="text-base flex items-center gap-2"><Mail className="w-4 h-4" />Report Templates</CardTitle></CardHeader>
          <CardContent>
            {templates.map(t => (
              <div key={t.id} className="flex items-center justify-between p-3 border rounded-lg mb-2" data-testid={`template-${t.id}`}>
                <div><p className="text-sm font-medium">{t.name}</p><p className="text-xs text-muted-foreground capitalize">{t.frequency} | {t.sections.length} sections</p></div>
                <Badge variant={t.enabled ? "default" : "outline"}>{t.enabled ? "Active" : "Off"}</Badge>
              </div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle className="text-base">Report History</CardTitle></CardHeader>
          <CardContent>
            {history.length === 0 ? <p className="text-sm text-muted-foreground py-4 text-center">No reports generated yet</p> :
              <Table>
                <TableHeader><TableRow><TableHead>Client</TableHead><TableHead>Period</TableHead><TableHead>Date</TableHead></TableRow></TableHeader>
                <TableBody>{history.map(h => (
                  <TableRow key={h.id} className="cursor-pointer" onClick={() => setCurrentReport(h)} data-testid={`report-${h.id}`}>
                    <TableCell className="font-medium">{h.client_name}</TableCell>
                    <TableCell className="text-xs">{h.period}</TableCell>
                    <TableCell className="text-xs">{new Date(h.generated_at).toLocaleDateString()}</TableCell>
                  </TableRow>
                ))}</TableBody>
              </Table>
            }
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
