import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import axios from "axios";
import { API, useAuth } from "@/App";
import OperationalPageHeader from "@/components/OperationalPageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { ArrowRight, CheckCircle2, Clock3, FileText, History, Laptop, MonitorUp, Play, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import NexusVerifiedSequence from "@/components/NexusVerifiedSequence";

export default function WorkSessionPage() {
  const { token } = useAuth(); const headers = useMemo(() => ({ Authorization: `Bearer ${token}` }), [token]); const [params, setParams] = useSearchParams();
  const [tickets, setTickets] = useState([]); const [brief, setBrief] = useState(null); const [busy, setBusy] = useState(false);
  const [nowTick, setNowTick] = useState(() => Date.now());
  const [draft, setDraft] = useState({ minutes: "", technical_notes: "", customer_summary: "", documentation_suggestion: "", recurrence_check: "", billing_classification: "", billable: true, verified: false });
  const ticketId = params.get("ticket") || "";
  const load = useCallback(async () => { try { const [ticketResponse, briefResponse] = await Promise.all([axios.get(`${API}/tickets`, { headers }), ticketId ? axios.get(`${API}/work-sessions/tickets/${ticketId}`, { headers }) : Promise.resolve({ data: null })]); setTickets(ticketResponse.data || []); setBrief(briefResponse.data); } catch (error) { toast.error(error.response?.data?.detail || "Work context could not be loaded"); } }, [headers, ticketId]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => {
    if (!brief?.active_session?.started_at) return undefined;
    const timer = window.setInterval(() => setNowTick(Date.now()), 30_000);
    return () => window.clearInterval(timer);
  }, [brief?.active_session?.started_at]);
  const elapsed = useMemo(() => {
    const startedAt = Date.parse(brief?.active_session?.started_at || "");
    if (Number.isNaN(startedAt)) return null;
    const totalMinutes = Math.max(0, Math.floor((nowTick - startedAt) / 60_000));
    const hours = Math.floor(totalMinutes / 60);
    return hours ? `${hours}h ${totalMinutes % 60}m` : `${totalMinutes}m`;
  }, [brief?.active_session?.started_at, nowTick]);
  const start = async () => { if (!ticketId) return; setBusy(true); try { await axios.post(`${API}/work-sessions/tickets/${ticketId}/start`, {}, { headers }); toast.success("Work session started"); await load(); } catch (e) { toast.error(e.response?.data?.detail || "Could not start work session"); } finally { setBusy(false); } };
  const complete = async () => { const session = brief?.active_session; if (!session) return; setBusy(true); try { await axios.post(`${API}/work-sessions/${session.id}/complete`, { ...draft, billing_classification: draft.billing_classification || brief?.scope_guardian?.recommended_classification || "review", minutes: Number(draft.minutes) }, { headers }); toast.success("Completion pack recorded"); await load(); } catch (e) { toast.error(e.response?.data?.detail || "Complete the required review fields"); } finally { setBusy(false); } };
  return <div className="nx-page-stage space-y-5 p-4 md:p-6" data-testid="work-session-page"><OperationalPageHeader eyebrow="Technician flow" title="Nexus Work Session" description="Turn accountable ticket work into reviewed time, resolution evidence and next actions—without duplicating admin." icon={Wrench} tone="sky" signal={brief?.active_session ? "working" : ticketId ? "recommendation" : undefined} />
    <Card><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><Label>Ticket</Label><Select value={ticketId} onValueChange={(ticket) => setParams({ ticket })}><SelectTrigger className="mt-1"><SelectValue placeholder="Choose a service ticket" /></SelectTrigger><SelectContent>{tickets.filter((ticket) => !["resolved", "closed"].includes(ticket.status)).map((ticket) => <SelectItem key={ticket.id} value={ticket.id}>{ticket.ticket_number || ticket.id.slice(0, 8)} · {ticket.title}</SelectItem>)}</SelectContent></Select></div>{brief?.ticket && <Link to={`/tickets?ticket=${brief.ticket.id}`} className="text-xs text-cyan-300 hover:text-cyan-100">Open ticket <ArrowRight className="inline h-3.5 w-3.5" /></Link>}</CardContent></Card>
    {!ticketId && <Card className="border-dashed"><CardContent className="py-20 text-center"><Wrench className="mx-auto mb-3 h-10 w-10 text-muted-foreground/40" /><p className="font-medium">Select a ticket to begin accountable work.</p><p className="mt-1 text-sm text-muted-foreground">Nexus will prepare the context; you remain in control of the completion pack.</p></CardContent></Card>}
    {ticketId && brief && <><section className="nx-ambient-surface rounded-2xl border border-cyan-400/20 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,0.13),transparent_48%),rgba(12,17,27,0.8)] p-5" data-nx-signal={brief.active_session ? "working" : "recommendation"}><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{brief.ticket.ticket_number || "Ticket"}</Badge><Badge variant="outline">{brief.ticket.status}</Badge></div><h2 className="mt-2 text-xl font-semibold">{brief.ticket.title}</h2><p className="mt-1 text-sm text-muted-foreground">{brief.ticket.client_name || "Client"} · {brief.device?.name || "No linked endpoint"}</p></div>{!brief.active_session ? <Button onClick={start} disabled={busy}><Play className="mr-2 h-4 w-4" />Start work</Button> : <Badge className="border-emerald-400/30 bg-emerald-400/10 px-3 py-2 text-emerald-200"><Clock3 className="mr-2 h-4 w-4" />Work session active</Badge>}</div></section>
      <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Sparkles className="h-4 w-4 text-cyan-300" />Session context</CardTitle><p className="text-xs text-muted-foreground">Nexus collects evidence for review; it does not infer a cause or perform a change.</p></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{brief.context.diagnostic_scope.map((item) => <div key={item} className="rounded-lg border border-border/70 bg-muted/[0.12] p-3 text-sm"><ShieldCheck className="mb-2 h-4 w-4 text-cyan-300" />{item}</div>)}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Laptop className="h-4 w-4 text-violet-300" />Remote</CardTitle></CardHeader><CardContent className="space-y-3">{brief.active_session && <div className="rounded-lg border border-cyan-400/20 bg-cyan-400/[0.06] p-3"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-cyan-200">Elapsed work</p><p className="mt-1 text-xl font-semibold text-cyan-50">{elapsed || "Calculating…"}</p><p className="mt-1 text-xs text-muted-foreground">Recorded as a suggestion only; review the final time entry.</p></div>}{brief.context.remote_available ? <Button className="w-full" variant="outline" onClick={() => window.open(`/remote-access?device=${brief.context.device_id}&ticket=${ticketId}`, "_blank")}><MonitorUp className="mr-2 h-4 w-4" />Launch remote</Button> : <p className="text-sm text-muted-foreground">Link a managed endpoint to enable governed remote access.</p>}</CardContent></Card></div>
      <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><History className="h-4 w-4 text-amber-300" />What changed recently</CardTitle><p className="text-xs text-muted-foreground">Client activity collected as context for this session—not a diagnosis.</p></CardHeader><CardContent>{brief.context.recent_changes?.length ? <div className="grid gap-3 lg:grid-cols-3">{brief.context.recent_changes.map((change, index) => <div key={`${change.at || change.title}-${index}`} className="rounded-lg border border-border/70 bg-muted/[0.12] p-3"><p className="text-sm font-medium">{change.title}</p><p className="mt-1 text-xs text-muted-foreground">{change.source || "Nexus"}{change.at ? ` · ${new Date(change.at).toLocaleString()}` : ""}</p></div>)}</div> : <p className="text-sm text-muted-foreground">No recent client activity is available yet.</p>}</CardContent></Card>
      <Card className={`border ${brief.scope_guardian?.status === "billable" ? "border-emerald-500/25 bg-emerald-500/[0.03]" : brief.scope_guardian?.status === "project" ? "border-violet-500/25 bg-violet-500/[0.03]" : "border-amber-500/25 bg-amber-500/[0.03]"}`}><CardHeader className="pb-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-4 w-4 text-amber-300" />Nexus Scope Guardian</CardTitle><p className="mt-1 text-xs text-muted-foreground">Nexus recommends a classification from linked agreement evidence. A technician always makes the final decision.</p></div><Badge variant="outline" className="capitalize">{brief.scope_guardian?.status?.replaceAll("_", " ") || "review"}</Badge></div></CardHeader><CardContent className="grid gap-4 lg:grid-cols-[1fr_240px]"><div><p className="text-sm font-medium">{brief.scope_guardian?.contract?.name || "No linked agreement"}</p><p className="mt-1 text-sm text-muted-foreground">{brief.scope_guardian?.reason}</p><p className="mt-2 text-xs text-amber-200/85">{brief.scope_guardian?.next_step}</p></div><div><Label>Work classification</Label><Select value={draft.billing_classification || brief.scope_guardian?.recommended_classification || "review"} onValueChange={(value) => setDraft({ ...draft, billing_classification: value, billable: ["billable", "project"].includes(value) })} disabled={!brief.active_session}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="included">Included in agreement</SelectItem><SelectItem value="billable">Billable work</SelectItem><SelectItem value="project">Project delivery</SelectItem><SelectItem value="approval_required">Approval required</SelectItem><SelectItem value="review">Needs commercial review</SelectItem></SelectContent></Select></div></CardContent></Card>
      <Card className={!brief.active_session ? "opacity-60" : ""}><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CheckCircle2 className="h-4 w-4 text-emerald-300" />Ready to complete</CardTitle><p className="text-xs text-muted-foreground">Review this pack before it becomes a time entry and durable ticket evidence. Customer communication remains a separate, explicit action.</p></CardHeader><CardContent className="space-y-5"><NexusVerifiedSequence complete={draft.verified ? 5 : brief.active_session ? 3 : 0} /><div className="grid gap-4 lg:grid-cols-2"><div><Label>Time to record (minutes)</Label><Input className="mt-1" type="number" min="1" value={draft.minutes} onChange={(e) => setDraft({ ...draft, minutes: e.target.value })} placeholder="37" disabled={!brief.active_session} /><Label className="mt-4 block">Technical resolution notes</Label><Textarea className="mt-1 min-h-28" value={draft.technical_notes} onChange={(e) => setDraft({ ...draft, technical_notes: e.target.value })} placeholder="What was observed, what was changed, and the technical result." disabled={!brief.active_session} /></div><div><Label>Customer-friendly update</Label><Textarea className="mt-1 min-h-20" value={draft.customer_summary} onChange={(e) => setDraft({ ...draft, customer_summary: e.target.value })} placeholder="Plain-language summary prepared for review; it will not send automatically." disabled={!brief.active_session} /><Label className="mt-4 block">Documentation / recurrence insight</Label><Textarea className="mt-1 min-h-20" value={draft.documentation_suggestion} onChange={(e) => setDraft({ ...draft, documentation_suggestion: e.target.value })} placeholder="Suggested documentation update or recurring condition." disabled={!brief.active_session} /><div className="mt-4 flex items-center gap-2"><Checkbox checked={draft.verified} onCheckedChange={(verified) => setDraft({ ...draft, verified: Boolean(verified) })} disabled={!brief.active_session} id="work-session-verified" /><Label htmlFor="work-session-verified">Resolution verified by technician</Label></div><div className="mt-3 flex items-center gap-2"><Checkbox checked={draft.billable} onCheckedChange={(billable) => setDraft({ ...draft, billable: Boolean(billable) })} disabled={!brief.active_session} id="work-session-billable" /><Label htmlFor="work-session-billable">Classify time as billable</Label></div></div></div></CardContent><div className="flex justify-end border-t px-6 py-4"><Button onClick={complete} disabled={busy || !brief.active_session || !draft.minutes || !draft.technical_notes || !draft.customer_summary}><FileText className="mr-2 h-4 w-4" />Review & complete</Button></div></Card>
    </>}</div>;
}
